#!/usr/bin/env python3
"""
One-time backfill for missing/garbled instruction text on MM's financial
question families -- Profit/Loss, Find Selling Price, Find Cost Price, and
Simple Interest (2026-09-15, Shailesh): "as for the profit and loss sheets
if we can backfill the sheets already assigned to the relevant students but
not yet attempted then it'll be really helpful, as the newly published ones
would obviously have the corrected logic."

Root cause: GenerateProfitLoss / GenerateFindSellingPrice /
GenerateFindCostPrice / GenerateSimpleInterest (app/question_engine/mm/
operands.py) all correctly set an ExtraMetadata["question_text"] key today
(e.g. "Find Profit", "Find Loss %", "Find Selling Price", "Find Simple
Interest"), and generator.py's assembly correctly promotes it to the
top-level question payload. Content generated by an OLDER version of these
generators never had that key at all, and that content is frozen forever at
generation time -- there is no code path that regenerates an already-created
question row. The result:
  - GeneratedQuestion (DPS) / CompetitionMockQuestion (Mock): question_text
    was simply left NULL.
  - AssessmentQuestion: a generic fallback (QuestionText() in
    assessment_engine_service.py, meant for genuinely operator-free
    generators) ran instead and got PERSISTED -- for a financial row whose
    "operators" are labels like ["Cost Price", "Selling Price"], not real
    math operators, this produces a nonsense caption (e.g. "3200 Selling
    Price 4500") rather than a blank. So an Assessment row here is detected
    by RECOMPUTING what its instruction should be and comparing, not just
    by a NULL check.

This script never touches operands_json/correct_answer/scoring in any
table -- only the question_text column, and only where deterministically
derivable from data already stored at generation time:
  - Every one of the four generators above always writes its own
    "concept_family" (via generator.py's metadata assembly, unconditionally)
    and, for PROFIT_LOSS specifically, an "answer_kind" ExtraMetadata key
    identifying which of its four variants (LOSS / LOSS_PERCENT /
    PROFIT_PERCENT / PROFIT) the row is -- both already exist in every
    row's metadata_json REGARDLESS of whether question_text itself was set,
    since concept_family/answer_kind were never the broken part. The
    mapping from (concept_family, answer_kind) -> question_text below is
    copied verbatim from what the CURRENT (fixed) generators themselves
    return, so this is a pure re-derivation of the exact same text current
    code would already produce for identical inputs -- never a guess.

Scope -- "assigned but not yet attempted", enforced per table:
  - DPS (GeneratedQuestion, via GeneratedQuestionSet): content is generated
    fresh per (student, DPS) -- confirmed via generation_service.py, which
    creates a brand-new GeneratedQuestionSet on every call, never reusing
    one across students. Backfilling one student's copy can therefore never
    affect another's. Touched only when: GeneratedQuestionSet.assignment_id
    is set and that Assignment.is_active is True, AND zero Attempt rows
    exist for (student_id, dps_id) -- any status at all, not just
    completed, so a student who merely started (IN_PROGRESS) is left alone
    too, since they've already seen whatever instruction was there.
  - Assessment (AssessmentQuestion) / Mock (CompetitionMockQuestion):
    UNLIKE DPS, one AssessmentVersion/CompetitionMockExam's questions are
    the SAME rows shared across every student assigned to it (confirmed:
    AssessmentVersion is keyed by blueprint_id, not student_id, and
    AssessmentAssignment's uq_assessment_assignment_student_version
    constraint allows many different students on one version). Editing a
    shared row while even ONE student has already attempted it would
    silently change what that student's already-submitted review page
    shows -- so the gate here is stricter: a version/exam is touched only
    when it has at least one assignment AND zero attempts anywhere,
    across every student, not just the student a caller might have in
    mind.

Annual Competition is out of scope entirely: confirmed via registry grep
that annual_competition_paper_registry.py carries no PROFIT_LOSS /
FIND_SELLING_PRICE / FIND_COST_PRICE / SIMPLE_INTEREST content at all today,
so there is nothing there to backfill.

Note on scope vs. the original report: Shailesh's own message named "the
profit and loss sheets" specifically. This script also backfills
SIMPLE_INTEREST, introduced in the exact same generator alongside
Profit/Loss and carrying the identical historical gap (same missing-
question_text mechanism, same fix). Flagged explicitly here and in the
run's own summary output rather than silently expanding scope -- the fix
itself is pure, additive, and zero-risk (text-only, same
assigned-but-unattempted gate), but the decision to widen the target set
beyond what was literally asked deserves to be visible, not assumed.

Safe by design:
  - Read-only detection/repair unless --apply.
  - Only ever writes the question_text column; every other column on every
    affected row (operands_json, correct_answer, metadata_json, etc.) is
    left completely untouched.
  - Idempotent: a row already carrying the correct text for its
    (concept_family, answer_kind) is left alone (reported as "already
    correct", not re-written); a second --apply run finds nothing left to
    fix.
  - Never touches a row once ANY attempt exists against it (DPS: for that
    exact student+DPS; Assessment/Mock: anywhere against that shared
    version/exam) -- scoring, review pages, and already-submitted content
    are never altered.

Usage (run from backend/, with the same DATABASE_URL the live backend uses):
    python scripts/backfill_mm_financial_instructions.py --dry-run
    python scripts/backfill_mm_financial_instructions.py --apply

--dry-run is the default if neither flag is passed. ALWAYS run --dry-run
first and read the summary before --apply.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import SessionLocal  # noqa: E402
from app.models.models import (  # noqa: E402
    Assignment,
    AssessmentAssignment,
    AssessmentAttempt,
    AssessmentQuestion,
    Attempt,
    CompetitionMockAssignment,
    CompetitionMockAttempt,
    CompetitionMockQuestion,
    GeneratedQuestion,
    GeneratedQuestionSet,
    Student,
    User,
)

# Force every print() to flush immediately -- same reasoning as the other
# backfill scripts in this directory (Windows terminal stdout buffering made
# a prior script look hung mid-run).
import builtins as _builtins  # noqa: E402

_real_print = _builtins.print


def print(*args, **kwargs):  # noqa: A001
    kwargs.setdefault("flush", True)
    _real_print(*args, **kwargs)


TARGET_CONCEPT_FAMILIES = {"PROFIT_LOSS", "FIND_SELLING_PRICE", "FIND_COST_PRICE", "SIMPLE_INTEREST"}

# Copied verbatim from GenerateProfitLoss's own Variant->QuestionText mapping
# (operands.py) -- "PROFIT" is that function's own default/else case, so an
# unrecognized or missing answer_kind (should never happen given every row
# always carries one, but historical data is exactly what this script exists
# to be skeptical of) falls back to the same default the generator itself
# uses, rather than skipping the row.
_PROFIT_LOSS_TEXT_BY_ANSWER_KIND = {
    "LOSS": "Find Loss",
    "LOSS_PERCENT": "Find Loss %",
    "PROFIT_PERCENT": "Find Profit %",
    "PROFIT": "Find Profit",
}
_FIXED_TEXT_BY_CONCEPT_FAMILY = {
    "FIND_SELLING_PRICE": "Find Selling Price",
    "FIND_COST_PRICE": "Find Cost Price",
    "SIMPLE_INTEREST": "Find Simple Interest",
}


def _SafeJson(Value, Fallback):
    if not Value:
        return Fallback
    try:
        return json.loads(Value)
    except (TypeError, ValueError):
        return Fallback


def _CorrectQuestionText(ConceptFamily: str, Metadata: dict) -> str | None:
    if ConceptFamily == "PROFIT_LOSS":
        return _PROFIT_LOSS_TEXT_BY_ANSWER_KIND.get(Metadata.get("answer_kind"), "Find Profit")
    return _FIXED_TEXT_BY_CONCEPT_FAMILY.get(ConceptFamily)


def _StudentLabel(db, student_id: str) -> str:
    student = db.get(Student, student_id)
    if not student:
        return student_id
    user = db.get(User, student.user_id) if student.user_id else None
    return f"{user.full_name} ({student.student_code})" if user else student.student_code


def _phase_dps(db, apply: bool) -> dict:
    print("-" * 88)
    print("PHASE 1: DPS (GeneratedQuestion) -- per-student content, backfilled per (student, DPS)")
    print("-" * 88)

    rows = db.query(GeneratedQuestion).all()
    checked = 0
    already_correct = 0
    skipped_not_assigned = 0
    skipped_already_attempted = 0
    fixed = 0
    qset_cache: dict[str, GeneratedQuestionSet] = {}
    assignment_cache: dict[str, Assignment | None] = {}
    # (student_id, dps_id) -> has any Attempt at all (any status)
    attempted_cache: dict[tuple[str, str], bool] = {}

    for row in rows:
        Metadata = _SafeJson(row.metadata_json, {})
        ConceptFamily = Metadata.get("concept_family")
        if ConceptFamily not in TARGET_CONCEPT_FAMILIES:
            continue
        checked += 1

        CorrectText = _CorrectQuestionText(ConceptFamily, Metadata)
        if not CorrectText or row.question_text == CorrectText:
            already_correct += 1
            continue

        qset = qset_cache.get(row.question_set_id)
        if qset is None:
            qset = db.get(GeneratedQuestionSet, row.question_set_id)
            qset_cache[row.question_set_id] = qset
        if qset is None or not qset.assignment_id:
            skipped_not_assigned += 1
            continue

        assignment = assignment_cache.get(qset.assignment_id, "__unset__")
        if assignment == "__unset__":
            assignment = db.get(Assignment, qset.assignment_id)
            assignment_cache[qset.assignment_id] = assignment
        if assignment is None or not assignment.is_active:
            skipped_not_assigned += 1
            continue

        AttemptKey = (qset.student_id, qset.dps_id)
        already_attempted = attempted_cache.get(AttemptKey)
        if already_attempted is None:
            already_attempted = (
                db.query(Attempt.id)
                .filter(Attempt.student_id == qset.student_id, Attempt.dps_id == qset.dps_id)
                .first()
                is not None
            )
            attempted_cache[AttemptKey] = already_attempted
        if already_attempted:
            skipped_already_attempted += 1
            continue

        fixed += 1
        print(f"  [FIX] {_StudentLabel(db, qset.student_id)} / DPS {qset.dps_id} / question {row.question_number}: "
              f"{row.question_text!r} -> {CorrectText!r}")
        if apply:
            row.question_text = CorrectText

    if apply:
        db.commit()
    print(f"\nDPS questions in target concept families checked: {checked}")
    print(f"  Already correct:                                {already_correct}")
    print(f"  Skipped (not actively assigned):                {skipped_not_assigned}")
    print(f"  Skipped (already attempted -- left untouched):  {skipped_already_attempted}")
    print(f"  {'Fixed' if apply else 'Would fix'}:                                          {fixed}")
    return {"checked": checked, "fixed": fixed}


def _phase_assessment(db, apply: bool) -> dict:
    print("\n" + "-" * 88)
    print("PHASE 2: Assessment (AssessmentQuestion) -- shared per assessment_version_id")
    print("-" * 88)

    rows = (
        db.query(AssessmentQuestion)
        .filter(AssessmentQuestion.concept_tag.in_(TARGET_CONCEPT_FAMILIES))
        .all()
    )
    by_version: dict[str, list[AssessmentQuestion]] = {}
    for row in rows:
        by_version.setdefault(row.assessment_version_id, []).append(row)

    checked = len(rows)
    already_correct = 0
    skipped_not_assigned = 0
    skipped_already_attempted = 0
    fixed = 0

    for version_id, version_rows in by_version.items():
        has_assignment = (
            db.query(AssessmentAssignment.id)
            .filter(AssessmentAssignment.assessment_version_id == version_id)
            .first()
            is not None
        )
        has_any_attempt = (
            db.query(AssessmentAttempt.id)
            .filter(AssessmentAttempt.assessment_version_id == version_id)
            .first()
            is not None
        )
        if not has_assignment:
            skipped_not_assigned += len(version_rows)
            continue
        if has_any_attempt:
            # Shared content -- even one attempt anywhere against this
            # version means editing it would silently change what an
            # already-submitted review page shows. Leave the WHOLE version
            # alone.
            skipped_already_attempted += len(version_rows)
            continue

        for row in version_rows:
            Metadata = _SafeJson(row.metadata_json, {})
            CorrectText = _CorrectQuestionText(row.concept_tag, Metadata)
            if not CorrectText or row.question_text == CorrectText:
                already_correct += 1
                continue
            fixed += 1
            print(f"  [FIX] assessment_version={version_id} / question {row.question_number}: "
                  f"{row.question_text!r} -> {CorrectText!r}")
            if apply:
                row.question_text = CorrectText

    if apply:
        db.commit()
    print(f"\nAssessment questions in target concept families checked: {checked}")
    print(f"  Already correct:                                        {already_correct}")
    print(f"  Skipped (version never assigned to anyone):             {skipped_not_assigned}")
    print(f"  Skipped (version has an attempt somewhere -- untouched): {skipped_already_attempted}")
    print(f"  {'Fixed' if apply else 'Would fix'}:                                                  {fixed}")
    return {"checked": checked, "fixed": fixed}


def _phase_mock(db, apply: bool) -> dict:
    print("\n" + "-" * 88)
    print("PHASE 3: Mock Exam (CompetitionMockQuestion) -- shared per mock_exam_id")
    print("-" * 88)

    rows = (
        db.query(CompetitionMockQuestion)
        .filter(CompetitionMockQuestion.concept_family.in_(TARGET_CONCEPT_FAMILIES))
        .all()
    )
    by_exam: dict[str, list[CompetitionMockQuestion]] = {}
    for row in rows:
        by_exam.setdefault(row.mock_exam_id, []).append(row)

    checked = len(rows)
    already_correct = 0
    skipped_not_assigned = 0
    skipped_already_attempted = 0
    fixed = 0

    for exam_id, exam_rows in by_exam.items():
        has_assignment = (
            db.query(CompetitionMockAssignment.id)
            .filter(CompetitionMockAssignment.mock_exam_id == exam_id)
            .first()
            is not None
        )
        has_any_attempt = (
            db.query(CompetitionMockAttempt.id)
            .filter(CompetitionMockAttempt.mock_exam_id == exam_id)
            .first()
            is not None
        )
        if not has_assignment:
            skipped_not_assigned += len(exam_rows)
            continue
        if has_any_attempt:
            skipped_already_attempted += len(exam_rows)
            continue

        for row in exam_rows:
            Metadata = _SafeJson(row.metadata_json, {})
            CorrectText = _CorrectQuestionText(row.concept_family, Metadata)
            if not CorrectText or row.question_text == CorrectText:
                already_correct += 1
                continue
            fixed += 1
            print(f"  [FIX] mock_exam={exam_id} / question {row.question_number}: "
                  f"{row.question_text!r} -> {CorrectText!r}")
            if apply:
                row.question_text = CorrectText

    if apply:
        db.commit()
    print(f"\nMock questions in target concept families checked: {checked}")
    print(f"  Already correct:                                  {already_correct}")
    print(f"  Skipped (exam never assigned to anyone):          {skipped_not_assigned}")
    print(f"  Skipped (exam has an attempt somewhere -- untouched): {skipped_already_attempted}")
    print(f"  {'Fixed' if apply else 'Would fix'}:                                            {fixed}")
    return {"checked": checked, "fixed": fixed}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true", help="Actually write corrections. Without this, runs as a dry-run preview.")
    parser.add_argument("--dry-run", action="store_true", help="Explicit dry-run (default behavior if --apply is omitted).")
    args = parser.parse_args()
    apply = bool(args.apply and not args.dry_run)

    print("=" * 88)
    print(f"MM FINANCIAL QUESTION INSTRUCTION BACKFILL -- mode: "
          f"{'APPLY (writing corrections)' if apply else 'DRY RUN (no changes will be written)'}")
    print(f"Target concept families: {sorted(TARGET_CONCEPT_FAMILIES)}")
    print("(Includes SIMPLE_INTEREST alongside the reported Profit/Loss family -- see this")
    print(" script's own module docstring, \"Note on scope vs. the original report\".)")
    print("=" * 88)

    db = SessionLocal()
    try:
        dps_summary = _phase_dps(db, apply)
        assessment_summary = _phase_assessment(db, apply)
        mock_summary = _phase_mock(db, apply)

        print("\n" + "=" * 88)
        print("OVERALL SUMMARY")
        print("=" * 88)
        total_fixed = dps_summary["fixed"] + assessment_summary["fixed"] + mock_summary["fixed"]
        print(f"DPS questions {'fixed' if apply else 'that would be fixed'}:        {dps_summary['fixed']}")
        print(f"Assessment questions {'fixed' if apply else 'that would be fixed'}: {assessment_summary['fixed']}")
        print(f"Mock questions {'fixed' if apply else 'that would be fixed'}:       {mock_summary['fixed']}")
        print(f"TOTAL:                                          {total_fixed}")
        if not apply:
            print("\nThis was a DRY RUN. Nothing was written. Re-run with --apply when ready.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
