#!/usr/bin/env python3
"""
One-time backfill for MM Add/Less Percentage answers that exceed the 5-total-
digit cap (2026-09-16, Shailesh): "the percentage backfill needs to be done
for the assigned but pending sheets, mocks, annual competition practice
papers ... regenerating and assigning them manually is gonna take a lot of
time so this needs to be done right now and accurately."

Root cause / forward-fix context: GeneratePercentageAddLess (app/question_
engine/mm/operands.py) now rejects any candidate answer over 5 total digits
(integer + decimal, trailing zeros excluded) before accepting it -- see that
function's own "MaxTotalDigits" comment, dated the same day as the report
this script answers. Content generated by the OLDER version of that function
never had this check, so some already-generated PERCENTAGE_ADD_LESS rows
carry an answer over the cap forever -- there is no code path that
regenerates an already-created question row on its own.

Unlike the sibling backfill_mm_financial_instructions.py (Profit/Loss etc.),
this is NOT a text-only fix. The thing that was wrong is the actual
correct_answer/operands -- the real math -- not just a display caption, so
"fixing" a violating row means regenerating that ONE question (operands,
correct_answer, and its multiple-choice options, which must stay consistent
with whatever the new correct_answer is) rather than rewriting a column in
place. This script does exactly that, and only that: it re-derives a single
question's content by calling the SAME production generator function
(GeneratePercentageAddLess) that real generation already uses today, so a
backfilled row is produced by identical code to a freshly generated one --
never a bespoke reimplementation of the math.

How a single row is regenerated faithfully without replaying an entire
DPS/mock/paper's generation (which would risk drifting every OTHER, already-
correct question in the same set, and for Mock/Annual-Competition would
require replaying admin-configurable section-registry state that may not be
perfectly reconstructible from stored data alone):
  - Every PERCENTAGE_ADD_LESS row's own metadata_json already carries
    "lesson_band" (the 1-6 difficulty band that drives its base/percent
    ranges) and "percentage_operator" ("x%" or "-%") -- both existed in this
    concept family's metadata BEFORE the digit-cap fix (confirmed via git
    history), so every historical row, violating or not, already carries
    them. Reading these two values back out of the row's own stored
    metadata and feeding them into a freshly built, minimal MMConfig
    (LessonNumber picked as any lesson that maps to the SAME stored band;
    DpsTitle forced to literally contain "add" or "less" to deterministically
    reproduce the SAME operator branch -- see GeneratePercentageAddLess's own
    title-sniffing logic) reproduces the exact same difficulty tier and
    Add-vs-Less type as the original, with nothing guessed.
  - GeneratePercentageAddLess is then called directly (not the full
    GenerateMmQuestionSet/_GenerateSingleSectionQuestionSet pipeline, which
    is built for generating a whole fresh set and would apply a
    duplicate-avoidance check meant to keep many sibling questions distinct
    -- irrelevant when replacing exactly one already-existing row), with a
    small bounded retry (mirroring _GenerateSingleSectionQuestionSet's own
    retry ceiling) that requires ValidateMmQuestion to accept the result --
    the same acceptance bar every other MM question in this codebase must
    clear.
  - Multiple-choice options are then rebuilt with the exact same
    GenerateMmDistractors/build_mcq_options calls generator.py itself uses
    for this concept family (Operation="GENERIC", the same classification
    _OperationKind gives PERCENTAGE_ADD_LESS), so the option set always
    matches the new correct_answer -- the previous options (built around the
    old, over-cap answer) are deleted, never left stale beside a new answer.
  - Only the columns that actually describe the MATH change: operands_json,
    operators_json, correct_answer, and the specific "what are the numbers"
    keys inside metadata_json (percentage_mode, base_amount,
    percentage_operator, percentage_workbook_rule, lakh_range_cap,
    two_part_only, add_percentage_max_numeric_digits,
    less_percentage_whole_numbers_only, correct_answer_max_total_digits).
    Every other metadata key -- module_code, level_code, lesson_number,
    dps_number, lesson_title, dps_title, section_number, section_title,
    concept_family, and so on, all of which describe WHERE this question
    lives, not what its numbers are -- is left completely untouched, so a
    backfilled row's context/audit trail is never overwritten with the
    synthetic placeholder Config values used only to steer regeneration. A
    "percentage_digit_cap_backfilled" / "percentage_digit_cap_backfilled_at"
    pair is added to metadata_json so a backfilled row is always visibly
    distinguishable later.

Scope -- "assigned but not yet attempted", enforced per table, mirroring
backfill_mm_financial_instructions.py's own safety gates exactly:
  - DPS (GeneratedQuestion, via GeneratedQuestionSet): touched only when
    GeneratedQuestionSet.assignment_id is set and that Assignment.is_active
    is True, AND zero Attempt rows exist for (student_id, dps_id) -- any
    status at all, not just completed.
  - Mock Exam (CompetitionMockQuestion, via CompetitionMockAssignment):
    UNLIKE DPS, one CompetitionMockExam's questions are the SAME rows shared
    across every student assigned to it, so the gate is stricter -- an exam
    is touched only when it has at least one CompetitionMockAssignment AND
    zero CompetitionMockAttempt rows anywhere, across every student.
  - Annual Competition practice papers: these are NOT a separate table --
    confirmed via annual_competition_studio_service.py that a practice paper
    is itself a CompetitionMockExam/CompetitionMockQuestion row, reached via
    a CompetitionEventLevelPaper bank-entry row (paper_kind == "PRACTICE",
    assigned_student_id set) rather than a CompetitionMockAssignment. A
    practice paper is touched only when its bank-entry row's consumed_at is
    still NULL (the model's own documented "not yet submitted" signal) AND
    zero CompetitionMockAttempt rows exist for (assigned_student_id,
    mock_exam_id) -- the same any-status gate as everywhere else, since
    consumed_at is only set at submission and a started-but-not-submitted
    attempt must not be disturbed either.
  - Annual Competition OFFICIAL papers are explicitly OUT of scope --
    Shailesh's own request named "assigned but pending sheets, mocks, annual
    competition practice papers" only. An official paper's
    CompetitionEventLevelPaper row (paper_kind == "OFFICIAL") is never
    queried by this script's practice-paper phase, and an official exam
    normally carries no CompetitionMockAssignment either, so it is not
    reachable via the mock phase's gate by construction.

Safe by design:
  - Read-only detection/repair unless --apply.
  - Never touches a row once ANY attempt exists against it (DPS: for that
    exact student+DPS; Mock/Practice: anywhere against that shared exam) --
    scoring, review pages, and already-submitted content are never altered.
  - Idempotent: a row whose answer is already within the 5-digit cap is left
    alone (reported as "already correct"); a second --apply run finds
    nothing left to fix, since the freshly regenerated answer is itself
    always cap-compliant (GeneratePercentageAddLess enforces this on every
    call, not just at first generation).
  - Every regenerated row is individually validated (ValidateMmQuestion)
    before being written -- a row that cannot produce a valid, cap-compliant
    replacement within the retry ceiling is reported and skipped, never
    force-written.

Usage (run from backend/, with the same DATABASE_URL the live backend uses):
    python scripts/backfill_mm_percentage_digit_cap.py --dry-run
    python scripts/backfill_mm_percentage_digit_cap.py --apply

--dry-run is the default if neither flag is passed. ALWAYS run --dry-run
first and read the summary before --apply.
"""
from __future__ import annotations

import argparse
import json
import random
import sys
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import SessionLocal  # noqa: E402
from app.models.models import (  # noqa: E402
    Assignment,
    Attempt,
    CompetitionEventLevelPaper,
    CompetitionMockAssignment,
    CompetitionMockAttempt,
    CompetitionMockExam,
    CompetitionMockQuestion,
    CompetitionMockQuestionOption,
    GeneratedQuestion,
    GeneratedQuestionSet,
    QuestionOption,
    Student,
    User,
)
from app.question_engine.mm.config import MMConfig  # noqa: E402
from app.question_engine.mm.distractors import GenerateMmDistractors  # noqa: E402
from app.question_engine.mm.generator import _Display, _OperationKind  # noqa: E402
from app.question_engine.mm.operands import GeneratePercentageAddLess, _TrimmedNumericDigitCount  # noqa: E402
from app.question_engine.mm.validators import ValidateMmQuestion  # noqa: E402
from app.question_engine.number_format import PlainNumberString  # noqa: E402
from app.question_engine.option_utils import build_mcq_options  # noqa: E402

# Force every print() to flush immediately -- same reasoning as every other
# backfill script in this directory.
import builtins as _builtins  # noqa: E402

_real_print = _builtins.print


def print(*args, **kwargs):  # noqa: A001
    kwargs.setdefault("flush", True)
    _real_print(*args, **kwargs)


MAX_TOTAL_DIGITS = 5
TARGET_CONCEPT_FAMILY = "PERCENTAGE_ADD_LESS"
MAX_REGENERATION_ATTEMPTS = 12

# Any lesson number that maps to a given band (_LessonBand: min(6, ((n-1)//5)+1))
# -- band 1 -> lesson 1, band 2 -> lesson 6, ... band 6 -> lesson 26+.
_REPRESENTATIVE_LESSON_FOR_BAND = {band: (band - 1) * 5 + 1 for band in range(1, 7)}

# Math-fact metadata keys that describe the regenerated NUMBERS -- these, and
# only these, get overwritten from the freshly regenerated ExtraMetadata.
# Every other existing metadata key (module_code, level_code, lesson_number,
# dps_title, section_title, concept_family, ...) is left completely alone.
_MATH_FACT_METADATA_KEYS = {
    "percentage_mode",
    "base_amount",
    "percentage_operator",
    "percentage_workbook_rule",
    "lakh_range_cap",
    "two_part_only",
    "add_percentage_max_numeric_digits",
    "less_percentage_whole_numbers_only",
    "correct_answer_max_total_digits",
}


class _RegenerationFailed(Exception):
    pass


def _SafeJson(Value, Fallback):
    if not Value:
        return Fallback
    try:
        return json.loads(Value)
    except (TypeError, ValueError):
        return Fallback


def _SafeDecimal(Value) -> Decimal | None:
    if Value is None:
        return None
    try:
        return Decimal(str(Value))
    except (InvalidOperation, ValueError, TypeError):
        return None


def _IsOverCap(CorrectAnswerText: str | None) -> bool:
    Value = _SafeDecimal(CorrectAnswerText)
    if Value is None:
        return False
    return _TrimmedNumericDigitCount(Value) > MAX_TOTAL_DIGITS


def _BuildRegenerationConfig(Metadata: dict, RowId: str) -> MMConfig:
    Band = int(Metadata.get("lesson_band") or 1)
    Band = min(6, max(1, Band))
    Operator = Metadata.get("percentage_operator")
    # DpsTitle must contain "less" xor "add" so GeneratePercentageAddLess's
    # own title-sniffing deterministically reproduces the SAME operator the
    # original row used -- see that function's own comment for the exact
    # substring logic this mirrors.
    DpsTitle = "Less Percentage Challenge" if Operator == "-%" else "Add Percentage Challenge"
    return MMConfig(
        ModuleCode="MM",
        LevelCode="MM-L1",
        LessonNumber=_REPRESENTATIVE_LESSON_FOR_BAND[Band],
        DpsNumber=1,
        DpsTitle=DpsTitle,
        LessonTitle=DpsTitle,
        QuestionCount=1,
        Seed=f"PCT-DIGIT-CAP-BACKFILL-{RowId}",
        ConceptFamily=TARGET_CONCEPT_FAMILY,
        GeneratorConfig={},
    )


def _RegenerateOne(Metadata: dict, RowId: str, QuestionNumber: int) -> tuple[list, list, Decimal, dict]:
    """Returns (Operands, Operators, CorrectAnswer, Options) for one freshly
    regenerated, validated, cap-compliant PERCENTAGE_ADD_LESS question, or
    raises _RegenerationFailed if no valid candidate is found within the
    retry ceiling (never force-writes an invalid/still-over-cap result)."""
    Config = _BuildRegenerationConfig(Metadata, RowId)
    BaseSeed = Config.Seed
    for Attempt in range(MAX_REGENERATION_ATTEMPTS):
        SeedText = BaseSeed if Attempt == 0 else f"{BaseSeed}-retry-{Attempt}"
        Rng = random.Random(SeedText)
        Operands, Operators, CorrectAnswer, ExtraMetadata = GeneratePercentageAddLess(Config, Rng, QuestionNumber)
        if not ValidateMmQuestion(Config, Operands, Operators, CorrectAnswer):
            continue
        if _TrimmedNumericDigitCount(CorrectAnswer) > MAX_TOTAL_DIGITS:
            # Should never happen post-fix, but this script exists to be
            # skeptical, not to trust -- never write a result that still
            # violates the exact thing it was run to correct.
            continue
        CorrectDisplay = _Display(CorrectAnswer)
        OperationKind = _OperationKind(Config.ConceptFamily)
        Distractors = GenerateMmDistractors(CorrectAnswer, Rng, AllowNegative=False, Operation=OperationKind, Operands=[])
        Options = build_mcq_options(CorrectDisplay, Distractors, Rng)
        MergedMetadata = dict(Metadata)
        for Key, Value in ExtraMetadata.items():
            if Key in _MATH_FACT_METADATA_KEYS:
                MergedMetadata[Key] = Value
        MergedMetadata["percentage_digit_cap_backfilled"] = True
        MergedMetadata["percentage_digit_cap_backfilled_at"] = datetime.now(timezone.utc).isoformat()
        return Operands, Operators, CorrectAnswer, {"options": Options, "metadata": MergedMetadata}
    raise _RegenerationFailed(f"Could not produce a valid, cap-compliant replacement for row {RowId} within {MAX_REGENERATION_ATTEMPTS} attempts.")


def _StudentLabel(db, student_id: str) -> str:
    student = db.get(Student, student_id)
    if not student:
        return student_id
    user = db.get(User, student.user_id) if student.user_id else None
    return f"{user.full_name} ({student.student_code})" if user else student.student_code


def _phase_dps(db, apply: bool) -> dict:
    print("-" * 88)
    print("PHASE 1: DPS (GeneratedQuestion) -- per-student content, backfilled per (student, DPS)")
    print("-" * 88)

    rows = (
        db.query(GeneratedQuestion)
        .join(GeneratedQuestionSet, GeneratedQuestion.question_set_id == GeneratedQuestionSet.id)
        .all()
    )
    checked = 0
    already_correct = 0
    skipped_not_assigned = 0
    skipped_already_attempted = 0
    fixed = 0
    failed = 0
    qset_cache: dict[str, GeneratedQuestionSet] = {}
    assignment_cache: dict[str, Assignment | None] = {}
    attempted_cache: dict[tuple[str, str], bool] = {}

    for row in rows:
        Metadata = _SafeJson(row.metadata_json, {})
        if Metadata.get("concept_family") != TARGET_CONCEPT_FAMILY:
            continue
        checked += 1

        if not _IsOverCap(row.correct_answer):
            already_correct += 1
            continue

        qset = qset_cache.get(row.question_set_id)
        if qset is None:
            qset = db.get(GeneratedQuestionSet, row.question_set_id)
            qset_cache[row.question_set_id] = qset
        if qset is None or not qset.assignment_id:
            skipped_not_assigned += 1
            continue

        assignment = assignment_cache.get(qset.assignment_id, "__unset__")
        if assignment == "__unset__":
            assignment = db.get(Assignment, qset.assignment_id)
            assignment_cache[qset.assignment_id] = assignment
        if assignment is None or not assignment.is_active:
            skipped_not_assigned += 1
            continue

        AttemptKey = (qset.student_id, qset.dps_id)
        already_attempted = attempted_cache.get(AttemptKey)
        if already_attempted is None:
            already_attempted = (
                db.query(Attempt.id)
                .filter(Attempt.student_id == qset.student_id, Attempt.dps_id == qset.dps_id)
                .first()
                is not None
            )
            attempted_cache[AttemptKey] = already_attempted
        if already_attempted:
            skipped_already_attempted += 1
            continue

        try:
            Operands, Operators, CorrectAnswer, Extra = _RegenerateOne(Metadata, row.id, row.question_number)
        except _RegenerationFailed as Error:
            failed += 1
            print(f"  [FAILED] {_StudentLabel(db, qset.student_id)} / DPS {qset.dps_id} / question {row.question_number}: {Error}")
            continue

        fixed += 1
        print(f"  [FIX] {_StudentLabel(db, qset.student_id)} / DPS {qset.dps_id} / question {row.question_number}: "
              f"{row.correct_answer!r} ({_TrimmedNumericDigitCount(_SafeDecimal(row.correct_answer) or Decimal(0))} digits) -> "
              f"{PlainNumberString(CorrectAnswer)!r} ({_TrimmedNumericDigitCount(CorrectAnswer)} digits)")
        if apply:
            row.operands_json = json.dumps(Operands)
            row.operators_json = json.dumps(Operators)
            row.correct_answer = PlainNumberString(CorrectAnswer)
            row.metadata_json = json.dumps(Extra["metadata"])
            db.query(QuestionOption).filter(QuestionOption.question_id == row.id).delete()
            for Option in Extra["options"]:
                db.add(QuestionOption(
                    question_id=row.id,
                    option_label=Option["label"],
                    option_value=PlainNumberString(Option["value"]),
                    is_correct=Option["is_correct"],
                    display_order=Option["display_order"],
                ))

    if apply:
        db.commit()
    print(f"\nDPS PERCENTAGE_ADD_LESS questions checked: {checked}")
    print(f"  Already within the 5-digit cap:                 {already_correct}")
    print(f"  Skipped (not actively assigned):                {skipped_not_assigned}")
    print(f"  Skipped (already attempted -- left untouched):  {skipped_already_attempted}")
    print(f"  Failed to produce a valid replacement:           {failed}")
    print(f"  {'Fixed' if apply else 'Would fix'}:                                          {fixed}")
    return {"checked": checked, "fixed": fixed, "failed": failed}


def _phase_mock(db, apply: bool) -> dict:
    print("\n" + "-" * 88)
    print("PHASE 2: Mock Exam (CompetitionMockQuestion) -- shared per mock_exam_id, via CompetitionMockAssignment")
    print("-" * 88)

    rows = db.query(CompetitionMockQuestion).all()
    by_exam: dict[str, list[CompetitionMockQuestion]] = {}
    for row in rows:
        Metadata = _SafeJson(row.metadata_json, {})
        if Metadata.get("concept_family") != TARGET_CONCEPT_FAMILY and row.concept_family != TARGET_CONCEPT_FAMILY:
            continue
        by_exam.setdefault(row.mock_exam_id, []).append(row)

    checked = sum(len(v) for v in by_exam.values())
    already_correct = 0
    skipped_not_assigned = 0
    skipped_already_attempted = 0
    fixed = 0
    failed = 0

    for exam_id, exam_rows in by_exam.items():
        has_assignment = (
            db.query(CompetitionMockAssignment.id)
            .filter(CompetitionMockAssignment.mock_exam_id == exam_id)
            .first()
            is not None
        )
        has_any_attempt = (
            db.query(CompetitionMockAttempt.id)
            .filter(CompetitionMockAttempt.mock_exam_id == exam_id)
            .first()
            is not None
        )
        if not has_assignment:
            skipped_not_assigned += len(exam_rows)
            continue
        if has_any_attempt:
            skipped_already_attempted += len(exam_rows)
            continue

        for row in exam_rows:
            Metadata = _SafeJson(row.metadata_json, {})
            if not _IsOverCap(row.correct_answer):
                already_correct += 1
                continue
            try:
                Operands, Operators, CorrectAnswer, Extra = _RegenerateOne(Metadata, row.id, row.question_number)
            except _RegenerationFailed as Error:
                failed += 1
                print(f"  [FAILED] mock_exam={exam_id} / question {row.question_number}: {Error}")
                continue
            fixed += 1
            print(f"  [FIX] mock_exam={exam_id} / question {row.question_number}: "
                  f"{row.correct_answer!r} -> {PlainNumberString(CorrectAnswer)!r}")
            if apply:
                row.operands_json = json.dumps(Operands)
                row.operators_json = json.dumps(Operators)
                row.correct_answer = PlainNumberString(CorrectAnswer)
                row.metadata_json = json.dumps(Extra["metadata"])
                db.query(CompetitionMockQuestionOption).filter(CompetitionMockQuestionOption.mock_question_id == row.id).delete()
                for Option in Extra["options"]:
                    db.add(CompetitionMockQuestionOption(
                        mock_question_id=row.id,
                        option_label=Option["label"],
                        option_value=PlainNumberString(Option["value"]),
                        is_correct=Option["is_correct"],
                        display_order=Option["display_order"],
                    ))

    if apply:
        db.commit()
    print(f"\nMock PERCENTAGE_ADD_LESS questions checked: {checked}")
    print(f"  Already within the 5-digit cap:           {already_correct}")
    print(f"  Skipped (exam never assigned to anyone):  {skipped_not_assigned}")
    print(f"  Skipped (exam has an attempt somewhere -- untouched): {skipped_already_attempted}")
    print(f"  Failed to produce a valid replacement:     {failed}")
    print(f"  {'Fixed' if apply else 'Would fix'}:                                    {fixed}")
    return {"checked": checked, "fixed": fixed, "failed": failed}


def _phase_annual_competition_practice(db, apply: bool) -> dict:
    print("\n" + "-" * 88)
    print("PHASE 3: Annual Competition PRACTICE papers (CompetitionMockQuestion via CompetitionEventLevelPaper bank)")
    print("-" * 88)

    practice_papers = (
        db.query(CompetitionEventLevelPaper)
        .filter(
            CompetitionEventLevelPaper.paper_kind == "PRACTICE",
            CompetitionEventLevelPaper.assigned_student_id.isnot(None),
            CompetitionEventLevelPaper.mock_exam_id.isnot(None),
        )
        .all()
    )

    checked = 0
    already_correct = 0
    skipped_consumed = 0
    skipped_already_attempted = 0
    fixed = 0
    failed = 0

    for paper in practice_papers:
        exam_rows = (
            db.query(CompetitionMockQuestion)
            .filter(CompetitionMockQuestion.mock_exam_id == paper.mock_exam_id)
            .all()
        )
        target_rows = []
        for row in exam_rows:
            Metadata = _SafeJson(row.metadata_json, {})
            if Metadata.get("concept_family") != TARGET_CONCEPT_FAMILY and row.concept_family != TARGET_CONCEPT_FAMILY:
                continue
            target_rows.append(row)
        if not target_rows:
            continue
        checked += len(target_rows)

        if paper.consumed_at is not None:
            skipped_consumed += len(target_rows)
            continue
        has_any_attempt = (
            db.query(CompetitionMockAttempt.id)
            .filter(
                CompetitionMockAttempt.mock_exam_id == paper.mock_exam_id,
                CompetitionMockAttempt.student_id == paper.assigned_student_id,
            )
            .first()
            is not None
        )
        if has_any_attempt:
            skipped_already_attempted += len(target_rows)
            continue

        for row in target_rows:
            Metadata = _SafeJson(row.metadata_json, {})
            if not _IsOverCap(row.correct_answer):
                already_correct += 1
                continue
            try:
                Operands, Operators, CorrectAnswer, Extra = _RegenerateOne(Metadata, row.id, row.question_number)
            except _RegenerationFailed as Error:
                failed += 1
                print(f"  [FAILED] {_StudentLabel(db, paper.assigned_student_id)} / practice paper={paper.id} / question {row.question_number}: {Error}")
                continue
            fixed += 1
            print(f"  [FIX] {_StudentLabel(db, paper.assigned_student_id)} / practice paper={paper.id} / question {row.question_number}: "
                  f"{row.correct_answer!r} -> {PlainNumberString(CorrectAnswer)!r}")
            if apply:
                row.operands_json = json.dumps(Operands)
                row.operators_json = json.dumps(Operators)
                row.correct_answer = PlainNumberString(CorrectAnswer)
                row.metadata_json = json.dumps(Extra["metadata"])
                db.query(CompetitionMockQuestionOption).filter(CompetitionMockQuestionOption.mock_question_id == row.id).delete()
                for Option in Extra["options"]:
                    db.add(CompetitionMockQuestionOption(
                        mock_question_id=row.id,
                        option_label=Option["label"],
                        option_value=PlainNumberString(Option["value"]),
                        is_correct=Option["is_correct"],
                        display_order=Option["display_order"],
                    ))

    if apply:
        db.commit()
    print(f"\nAnnual Competition practice PERCENTAGE_ADD_LESS questions checked: {checked}")
    print(f"  Already within the 5-digit cap:                {already_correct}")
    print(f"  Skipped (paper already consumed/submitted):    {skipped_consumed}")
    print(f"  Skipped (an attempt exists -- untouched):      {skipped_already_attempted}")
    print(f"  Failed to produce a valid replacement:          {failed}")
    print(f"  {'Fixed' if apply else 'Would fix'}:                                         {fixed}")
    return {"checked": checked, "fixed": fixed, "failed": failed}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true", help="Actually write corrections. Without this, runs as a dry-run preview.")
    parser.add_argument("--dry-run", action="store_true", help="Explicit dry-run (default behavior if --apply is omitted).")
    args = parser.parse_args()
    apply = bool(args.apply and not args.dry_run)

    print("=" * 88)
    print(f"MM PERCENTAGE ADD/LESS DIGIT-CAP BACKFILL -- mode: "
          f"{'APPLY (writing corrections)' if apply else 'DRY RUN (no changes will be written)'}")
    print(f"Target concept family: {TARGET_CONCEPT_FAMILY}   Cap: {MAX_TOTAL_DIGITS} total digits")
    print("=" * 88)

    db = SessionLocal()
    try:
        dps_summary = _phase_dps(db, apply)
        mock_summary = _phase_mock(db, apply)
        practice_summary = _phase_annual_competition_practice(db, apply)

        print("\n" + "=" * 88)
        print("OVERALL SUMMARY")
        print("=" * 88)
        total_fixed = dps_summary["fixed"] + mock_summary["fixed"] + practice_summary["fixed"]
        total_failed = dps_summary["failed"] + mock_summary["failed"] + practice_summary["failed"]
        print(f"DPS questions {'fixed' if apply else 'that would be fixed'}:                       {dps_summary['fixed']}")
        print(f"Mock questions {'fixed' if apply else 'that would be fixed'}:                      {mock_summary['fixed']}")
        print(f"Annual Competition practice questions {'fixed' if apply else 'that would be fixed'}: {practice_summary['fixed']}")
        print(f"TOTAL FIXED:                                             {total_fixed}")
        if total_failed:
            print(f"TOTAL FAILED (see [FAILED] lines above -- left untouched, needs manual review): {total_failed}")
        if not apply:
            print("\nThis was a DRY RUN. Nothing was written. Re-run with --apply when ready.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
