export type AdminStudent = {
  studentId: string;
  userId: string;
  customId: string | null;
  teacher: string | null;
  teacherId: string | null;
  teacherCode: string | null;
  teacherName: string | null;
  admissionDate: string | null;
  studentName: string;
  fullName: string;
  dob: string | null;
  gender: string | null;
  bloodGroup: string | null;
  interest: string | null;
  photoUrl: string | null;
  signatureUrl: string | null;
  presentAddress: string | null;
  permanentAddress: string | null;
  schoolName: string | null;
  schoolArea: string | null;
  className: string | null;
  section: string | null;
  fatherName: string | null;
  fatherOccupation: string | null;
  fatherMobile: string | null;
  fatherEmail: string | null;
  fatherWhatsapp: string | null;
  motherName: string | null;
  motherOccupation: string | null;
  motherMobile: string | null;
  motherEmail: string | null;
  motherWhatsapp: string | null;
  studentCode: string;
  currentModuleId: string | null;
  currentModuleCode: string | null;
  currentModuleName: string | null;
  currentLevelId: string | null;
  currentLevelCode: string | null;
  currentLevelName: string | null;
  status: "ACTIVE" | "INACTIVE" | string;
  isActive: boolean;
  createdAt: string | null;
};

export type StudentProfilePayload = {
  customId: string;
  teacher: string;
  teacherId?: string | null;
  teacherCode?: string | null;
  admissionDate: string;
  studentName: string;
  dob: string;
  gender: string;
  bloodGroup: string;
  schoolName: string;
  className: string;
  section: string;
  fatherName: string;
  fatherMobile: string;
  fatherEmail: string;
  fatherWhatsapp: string;
  motherName: string;
  motherMobile: string;
  motherEmail: string;
  motherWhatsapp: string;
  studentCode: string;
  password?: string;
  currentModuleId: string;
  currentLevelId: string;
  moduleCode?: string | null;
  levelCode?: string | null;
  status: "ACTIVE" | "INACTIVE";
  interest?: string | null;
  presentAddress?: string | null;
  permanentAddress?: string | null;
  schoolArea?: string | null;
  fatherOccupation?: string | null;
  motherOccupation?: string | null;
};

export type BulkUploadResult = {
  created: number;
  failed: number;
  skipped?: number;
  totalRows?: number;
  unknownColumns?: string[];
  results: Array<{
    row: number;
    status: "CREATED" | "FAILED" | string;
    studentCode?: string;
    studentName?: string;
    teacherCode?: string | null;
    levelCode?: string | null;
    error?: string;
  }>;
};
