export type PopArtStyle = 
  | 'cyberpunk' | 'neon' | 'retro' | 'synthwave' | 'hologram' 
  | 'glitch' | 'comic' | 'glassmorphism' | 'brutalist' | 'minimal'
  | 'cosmic' | 'magma' | 'biohazard' | 'frost' | 'gold';

export interface MotivationQuote {
  id: string;
  text: string;
  author: string | null;
  style: PopArtStyle;
}

export const POP_ART_STYLES: Record<PopArtStyle, { containerClass: string; textClass: string; authorClass: string; iconBoxClass: string }> = {
  cyberpunk: {
    containerClass: "bg-yellow-400 dark:bg-yellow-400 border-4 border-black dark:border-black shadow-[8px_8px_0px_rgba(0,0,0,1)] bg-[url('/noise.png')] opacity-100",
    textClass: "text-black font-black uppercase tracking-tighter drop-shadow-md",
    authorClass: "bg-black text-yellow-400 px-3 py-1 font-mono font-bold uppercase",
    iconBoxClass: "bg-black text-yellow-400 border-2 border-black"
  },
  neon: {
    containerClass: "bg-fuchsia-950/80 dark:bg-fuchsia-950 border border-fuchsia-500 shadow-[0_0_30px_rgba(217,70,239,0.4)] backdrop-blur-md opacity-100",
    textClass: "text-fuchsia-100 font-sans font-black tracking-wide drop-shadow-[0_0_10px_rgba(217,70,239,0.8)]",
    authorClass: "text-fuchsia-300 font-medium tracking-widest uppercase",
    iconBoxClass: "bg-fuchsia-500/20 text-fuchsia-400 border border-fuchsia-500/50"
  },
  retro: {
    containerClass: "bg-[#fdf6e3] dark:bg-[#1e293b] border-4 border-[#2aa198] dark:border-[#2aa198] border-dashed shadow-[0_0_15px_rgba(42,161,152,0.3)] bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-100",
    textClass: "text-[#073642] dark:text-[#2aa198] font-mono font-bold tracking-tight drop-shadow-sm",
    authorClass: "bg-[#2aa198] text-white px-2 font-mono font-bold",
    iconBoxClass: "bg-[#2aa198]/10 text-[#2aa198] border-2 border-[#2aa198]"
  },
  synthwave: {
    containerClass: "bg-gradient-to-br from-purple-900 via-violet-900 to-indigo-900 border-t-2 border-pink-500 shadow-[0_0_40px_rgba(236,72,153,0.3)] bg-[url('https://www.transparenttextures.com/patterns/grid-me.png')] opacity-100",
    textClass: "text-transparent bg-clip-text bg-gradient-to-r from-pink-400 to-cyan-400 font-black italic tracking-tighter drop-shadow-[0_2px_2px_rgba(0,0,0,0.8)]",
    authorClass: "text-cyan-400 font-mono text-sm tracking-widest",
    iconBoxClass: "bg-pink-500/20 text-cyan-400 border border-pink-500/50"
  },
  hologram: {
    containerClass: "bg-cyan-50/90 dark:bg-cyan-950/40 border border-cyan-400/50 shadow-[inset_0_0_30px_rgba(34,211,238,0.2)] backdrop-blur-xl opacity-100",
    textClass: "text-cyan-800 dark:text-cyan-300 font-sans font-light tracking-wide",
    authorClass: "text-cyan-600 dark:text-cyan-500 font-medium tracking-widest uppercase",
    iconBoxClass: "bg-cyan-400/10 text-cyan-500 border border-cyan-400/30"
  },
  glitch: {
    containerClass: "bg-slate-100 dark:bg-black border-l-8 border-red-500 shadow-[4px_0_0_rgba(59,130,246,0.5)] opacity-100",
    textClass: "text-slate-900 dark:text-white font-black tracking-tighter uppercase drop-shadow-[2px_2px_0px_rgba(239,68,68,0.7)]",
    authorClass: "bg-red-500 text-white px-2 font-bold italic",
    iconBoxClass: "bg-red-500/10 text-red-500 border-2 border-red-500"
  },
  comic: {
    containerClass: "bg-blue-100 dark:bg-blue-600 border-4 border-black shadow-[6px_6px_0px_rgba(0,0,0,1)] bg-[url('https://www.transparenttextures.com/patterns/polka-dots.png')] opacity-100",
    textClass: "text-black font-black uppercase tracking-tight drop-shadow-[2px_2px_0px_white]",
    authorClass: "bg-yellow-400 text-black px-3 py-1 font-bold border-2 border-black rotate-[-2deg]",
    iconBoxClass: "bg-yellow-400 text-black border-2 border-black"
  },
  glassmorphism: {
    containerClass: "bg-white/40 dark:bg-white/5 border border-white/40 shadow-[0_8px_32px_0_rgba(31,38,135,0.2)] backdrop-blur-2xl opacity-100 rounded-3xl",
    textClass: "text-slate-800 dark:text-white font-medium tracking-tight",
    authorClass: "text-slate-600 dark:text-slate-300 font-semibold uppercase tracking-widest",
    iconBoxClass: "bg-white/20 text-slate-800 dark:text-white border border-white/30"
  },
  brutalist: {
    containerClass: "bg-zinc-200 dark:bg-zinc-900 border-4 border-zinc-950 dark:border-zinc-100 opacity-100",
    textClass: "text-zinc-950 dark:text-zinc-100 font-black uppercase tracking-tighter",
    authorClass: "bg-zinc-950 dark:bg-zinc-100 text-zinc-100 dark:text-zinc-900 px-4 py-2 font-bold uppercase",
    iconBoxClass: "bg-zinc-300 dark:bg-zinc-800 text-zinc-950 dark:text-zinc-100 border-4 border-zinc-950 dark:border-zinc-100"
  },
  minimal: {
    containerClass: "bg-white dark:bg-black border border-gray-200 dark:border-gray-800 opacity-100",
    textClass: "text-black dark:text-white font-serif italic tracking-wide",
    authorClass: "text-gray-400 font-sans text-xs tracking-widest uppercase",
    iconBoxClass: "bg-gray-100 dark:bg-gray-900 text-black dark:text-white"
  },
  cosmic: {
    containerClass: "bg-slate-900 border border-indigo-500/30 shadow-[0_0_50px_rgba(99,102,241,0.2)] bg-[url('https://www.transparenttextures.com/patterns/stardust.png')] opacity-100",
    textClass: "text-indigo-100 font-light tracking-widest drop-shadow-[0_0_8px_rgba(165,180,252,0.8)]",
    authorClass: "text-indigo-400 font-bold tracking-widest uppercase",
    iconBoxClass: "bg-indigo-900/50 text-indigo-300 border border-indigo-500/50"
  },
  magma: {
    containerClass: "bg-orange-950/90 border-b-4 border-orange-500 shadow-[0_10px_40px_rgba(249,115,22,0.3)] opacity-100",
    textClass: "text-orange-100 font-black tracking-tight drop-shadow-[0_2px_4px_rgba(234,88,12,1)]",
    authorClass: "text-orange-400 font-bold uppercase",
    iconBoxClass: "bg-orange-600/20 text-orange-400 border border-orange-500/50"
  },
  biohazard: {
    containerClass: "bg-lime-50 dark:bg-lime-950 border-4 border-lime-500 shadow-[0_0_20px_rgba(132,204,22,0.4)] opacity-100",
    textClass: "text-lime-900 dark:text-lime-400 font-mono font-bold tracking-tighter drop-shadow-sm",
    authorClass: "bg-lime-500 text-lime-950 px-2 font-mono font-black",
    iconBoxClass: "bg-lime-500/20 text-lime-600 dark:text-lime-400 border-2 border-lime-500"
  },
  frost: {
    containerClass: "bg-sky-50/80 dark:bg-sky-950/60 border border-sky-300 shadow-[0_0_30px_rgba(125,211,252,0.3)] backdrop-blur-md opacity-100",
    textClass: "text-sky-900 dark:text-sky-100 font-sans font-medium tracking-wide",
    authorClass: "text-sky-600 dark:text-sky-400 font-bold uppercase tracking-widest",
    iconBoxClass: "bg-sky-200/50 dark:bg-sky-800/50 text-sky-700 dark:text-sky-300 border border-sky-400"
  },
  gold: {
    containerClass: "bg-amber-100 dark:bg-amber-950 border-2 border-amber-500 shadow-[0_0_40px_rgba(245,158,11,0.2)] opacity-100",
    textClass: "text-amber-900 dark:text-amber-200 font-serif font-black tracking-normal drop-shadow-sm",
    authorClass: "text-amber-700 dark:text-amber-500 font-serif italic tracking-widest",
    iconBoxClass: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500"
  }
};

export const GAMER_MOTIVATIONS: MotivationQuote[] = [
  { id: "0", text: "The difference between a master and a beginner is that the master has failed more times than the beginner has even tried.", author: "Kobe Bryant", style: "glitch" },
  { id: "1", text: "A flawless run isn't luck. It's a thousand invisible mistakes corrected.", author: "Michael Jordan", style: "minimal" },
  { id: "2", text: "Precision beats power. Timing beats speed.", author: "Steve Jobs", style: "retro" },
  { id: "3", text: "The obstacle is the way.", author: "Kobe Bryant", style: "biohazard" },
  { id: "4", text: "What stands in the way becomes the way.", author: "Naval Ravikant", style: "glitch" },
  { id: "5", text: "You have power over your mind - not outside events.", author: "Carl Friedrich Gauss", style: "magma" },
  { id: "6", text: "The more you sweat in practice, the less you bleed in battle.", author: "Isaac Newton", style: "synthwave" },
  { id: "7", text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Seneca", style: "glassmorphism" },
  { id: "8", text: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", author: "Paul Graham", style: "neon" },
  { id: "9", text: "There is no elevator to success, you have to take the stairs.", author: "John von Neumann", style: "minimal" },
  { id: "10", text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Alan Turing", style: "brutalist" },
  { id: "11", text: "In the middle of difficulty lies opportunity.", author: "Bruce Lee", style: "biohazard" },
  { id: "12", text: "Pure mathematics is, in its way, the poetry of logical ideas.", author: "Steve Jobs", style: "cyberpunk" },
  { id: "13", text: "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.", author: "Isaac Newton", style: "brutalist" },
  { id: "14", text: "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is.", author: "Bruce Lee", style: "minimal" },
  { id: "15", text: "The essence of mathematics is not to make simple things complicated, but to make complicated things simple.", author: "Naval Ravikant", style: "retro" },
  { id: "16", text: "Genius is 1% talent and 99% hard work.", author: "Bruce Lee", style: "cosmic" },
  { id: "17", text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Ada Lovelace", style: "synthwave" },
  { id: "18", text: "Every strike brings me closer to the next home run.", author: "Elon Musk", style: "gold" },
  { id: "19", text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Naval Ravikant", style: "hologram" },
  { id: "20", text: "The only way to do great work is to love what you do.", author: "Epictetus", style: "biohazard" },
  { id: "21", text: "Focus is a matter of deciding what things you're not going to do.", author: "Sun Tzu", style: "gold" },
  { id: "22", text: "The best way to predict the future is to invent it.", author: "Michael Jordan", style: "synthwave" },
  { id: "23", text: "Stay hungry, stay foolish.", author: "Michael Jordan", style: "frost" },
  { id: "24", text: "You miss 100% of the shots you don't take.", author: "Seneca", style: "cosmic" },
  { id: "25", text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Sun Tzu", style: "cosmic" },
  { id: "26", text: "Talent wins games, but teamwork and intelligence win championships.", author: "Leonhard Euler", style: "comic" },
  { id: "27", text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Epictetus", style: "glassmorphism" },
  { id: "28", text: "I've failed over and over and over again in my life. And that is why I succeed.", author: "David Goggins", style: "glitch" },
  { id: "29", text: "If you're afraid to fail, then you're probably going to fail.", author: "Naval Ravikant", style: "gold" },
  { id: "30", text: "Don't count the days, make the days count.", author: "John von Neumann", style: "magma" },
  { id: "31", text: "Float like a butterfly, sting like a bee.", author: "David Goggins", style: "synthwave" },
  { id: "32", text: "The fight is won or lost far away from witnesses.", author: "Kobe Bryant", style: "magma" },
  { id: "33", text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Sun Tzu", style: "cyberpunk" },
  { id: "34", text: "It's hard to beat a person who never gives up.", author: "Michael Jordan", style: "glassmorphism" },
  { id: "35", text: "Quality is not an act, it is a habit.", author: "Sun Tzu", style: "magma" },
  { id: "36", text: "Well done is better than well said.", author: "Epictetus", style: "comic" },
  { id: "37", text: "The secret of getting ahead is getting started.", author: "Socrates", style: "cyberpunk" },
  { id: "38", text: "It does not matter how slowly you go as long as you do not stop.", author: "John von Neumann", style: "synthwave" },
  { id: "39", text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Albert Einstein", style: "biohazard" },
  { id: "40", text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Paul Graham", style: "frost" },
  { id: "41", text: "No man has the right to be an amateur in the matter of physical training.", author: "Marcus Aurelius", style: "comic" },
  { id: "42", text: "Be intolerant of your own ignorance.", author: "Aristotle", style: "glitch" },
  { id: "43", text: "First, master the fundamentals.", author: "Isaac Newton", style: "cyberpunk" },
  { id: "44", text: "Knowledge speaks, but wisdom listens.", author: "Paul Graham", style: "biohazard" },
  { id: "45", text: "The mind is everything. What you think you become.", author: "Michael Jordan", style: "brutalist" },
  { id: "46", text: "The unexamined life is not worth living.", author: "David Goggins", style: "neon" },
  { id: "47", text: "Happiness depends upon ourselves.", author: "Alan Turing", style: "neon" },
  { id: "48", text: "Nature does nothing in vain.", author: "Albert Einstein", style: "magma" },
  { id: "49", text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", style: "cyberpunk" },
  { id: "50", text: "The only true wisdom is in knowing you know nothing.", author: "Sam Altman", style: "brutalist" },
  { id: "51", text: "There is no genius without some touch of madness.", author: "Steve Jobs", style: "neon" },
  { id: "52", text: "Great acts are made up of small deeds.", author: "David Goggins", style: "retro" },
  { id: "53", text: "Learning never exhausts the mind.", author: "Michael Jordan", style: "frost" },
  { id: "54", text: "Nothing is impossible for him who will try.", author: "Carl Friedrich Gauss", style: "neon" },
  { id: "55", text: "The roots of education are bitter, but the fruit is sweet.", author: "Elon Musk", style: "glitch" },
  { id: "56", text: "The energy of the mind is the essence of life.", author: "Socrates", style: "brutalist" },
  { id: "57", text: "He who has overcome his fears will truly be free.", author: "Sun Tzu", style: "synthwave" },
  { id: "58", text: "We make war that we may live in peace.", author: "Elon Musk", style: "minimal" },
  { id: "59", text: "Courage is the first of human qualities because it is the quality which guarantees the others.", author: "John von Neumann", style: "brutalist" },
  { id: "60", text: "Difficulties strengthen the mind, as labor does the body.", author: "Alan Turing", style: "gold" },
  { id: "61", text: "A journey of a thousand miles begins with a single step.", author: "David Goggins", style: "brutalist" },
  { id: "62", text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Elon Musk", style: "frost" },
  { id: "63", text: "Mastering others is strength; mastering yourself is true power.", author: "John von Neumann", style: "retro" },
  { id: "64", text: "The best fighter is never angry.", author: "Ada Lovelace", style: "brutalist" },
  { id: "65", text: "When you are content to be simply yourself and don't compare or compete, everybody will respect you.", author: "Miyamoto Musashi", style: "synthwave" },
  { id: "66", text: "Anticipate the difficult by managing the easy.", author: "Isaac Newton", style: "glassmorphism" },
  { id: "67", text: "To lead people walk behind them.", author: "Seneca", style: "glassmorphism" },
  { id: "68", text: "Silence is a source of great strength.", author: "Seneca", style: "frost" },
  { id: "69", text: "He who knows, does not speak. He who speaks, does not know.", author: "Ada Lovelace", style: "magma" },
  { id: "70", text: "The wise man does not lay up his own treasures. The more he gives to others, the more he has for his own.", author: "Ada Lovelace", style: "comic" },
  { id: "71", text: "Life is a series of natural and spontaneous changes.", author: "Paul Graham", style: "magma" },
  { id: "72", text: "Act without expectation.", author: "Paul Graham", style: "minimal" },
  { id: "73", text: "Care about what other people think and you will always be their prisoner.", author: "Carl Friedrich Gauss", style: "glassmorphism" },
  { id: "74", text: "Nature does not hurry, yet everything is accomplished.", author: "Socrates", style: "brutalist" },
  { id: "75", text: "Do the difficult things while they are easy and do the great things while they are small.", author: "Michael Jordan", style: "neon" },
  { id: "76", text: "If you correct your mind, the rest of your life will fall into place.", author: "Miyamoto Musashi", style: "glassmorphism" },
  { id: "77", text: "The softest things in the world overcome the hardest things in the world.", author: "Epictetus", style: "comic" },
  { id: "78", text: "Those who know do not speak. Those who speak do not know.", author: "Elon Musk", style: "neon" },
  { id: "79", text: "A good traveler has no fixed plans and is not intent on arriving.", author: "Epictetus", style: "hologram" },
  { id: "80", text: "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.", author: "Seneca", style: "gold" },
  { id: "81", text: "Be still like a mountain and flow like a great river.", author: "Socrates", style: "hologram" },
  { id: "82", text: "Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend.", author: "Sun Tzu", style: "brutalist" },
  { id: "83", text: "Simplicity is the ultimate sophistication.", author: "Aristotle", style: "brutalist" },
  { id: "84", text: "Art is never finished, only abandoned.", author: "Steve Jobs", style: "cosmic" },
  { id: "85", text: "Where the spirit does not work with the hand, there is no art.", author: "Michael Jordan", style: "glassmorphism" },
  { id: "86", text: "Tears come from the heart and not from the brain.", author: "Seneca", style: "brutalist" },
  { id: "87", text: "As a well-spent day brings happy sleep, so a life well spent brings happy death.", author: "Sam Altman", style: "synthwave" },
  { id: "88", text: "The greatest deception men suffer is from their own opinions.", author: "Kobe Bryant", style: "frost" },
  { id: "89", text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.", author: "Aristotle", style: "brutalist" },
  { id: "90", text: "Nothing can be loved or hated unless it is first understood.", author: "Epictetus", style: "glassmorphism" },
  { id: "91", text: "Experience never errs; it is only your judgments that err.", author: "Ada Lovelace", style: "cyberpunk" },
  { id: "92", text: "He who loves practice without theory is like the sailor who boards ship without a rudder and compass.", author: "Leonhard Euler", style: "hologram" },
  { id: "93", text: "While I thought that I was learning how to live, I have been learning how to die.", author: "Steve Jobs", style: "frost" },
  { id: "94", text: "Intellectual passion drives out sensuality.", author: "John von Neumann", style: "hologram" },
  { id: "95", text: "All our knowledge has its origins in our perceptions.", author: "Leonhard Euler", style: "minimal" },
  { id: "96", text: "Iron rusts from disuse; water loses its purity from stagnation... even so does inaction sap the vigor of the mind.", author: "Miyamoto Musashi", style: "frost" },
  { id: "97", text: "Make your work to be in keeping with your purpose.", author: "Naval Ravikant", style: "synthwave" },
  { id: "98", text: "The truth of things is the chief nutriment of superior intellects.", author: "Michael Jordan", style: "hologram" },
  { id: "99", text: "A beautiful body perishes, but a work of art dies not.", author: "Richard Feynman", style: "hologram" },
  { id: "100", text: "The difference between a master and a beginner is that the master has failed more times than the beginner has even tried.", author: "Sam Altman", style: "comic" },
  { id: "101", text: "A flawless run isn't luck. It's a thousand invisible mistakes corrected.", author: "Marcus Aurelius", style: "brutalist" },
  { id: "102", text: "Precision beats power. Timing beats speed.", author: "Steve Jobs", style: "biohazard" },
  { id: "103", text: "The obstacle is the way.", author: "Albert Einstein", style: "hologram" },
  { id: "104", text: "What stands in the way becomes the way.", author: "Aristotle", style: "cosmic" },
  { id: "105", text: "You have power over your mind - not outside events.", author: "Isaac Newton", style: "comic" },
  { id: "106", text: "The more you sweat in practice, the less you bleed in battle.", author: "Steve Jobs", style: "neon" },
  { id: "107", text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Carl Friedrich Gauss", style: "frost" },
  { id: "108", text: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", author: "John von Neumann", style: "biohazard" },
  { id: "109", text: "There is no elevator to success, you have to take the stairs.", author: "Ada Lovelace", style: "frost" },
  { id: "110", text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Elon Musk", style: "neon" },
  { id: "111", text: "In the middle of difficulty lies opportunity.", author: "Sam Altman", style: "comic" },
  { id: "112", text: "Pure mathematics is, in its way, the poetry of logical ideas.", author: "Leonhard Euler", style: "retro" },
  { id: "113", text: "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.", author: "Aristotle", style: "frost" },
  { id: "114", text: "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is.", author: "Paul Graham", style: "glassmorphism" },
  { id: "115", text: "The essence of mathematics is not to make simple things complicated, but to make complicated things simple.", author: "Ada Lovelace", style: "synthwave" },
  { id: "116", text: "Genius is 1% talent and 99% hard work.", author: "Elon Musk", style: "cosmic" },
  { id: "117", text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Socrates", style: "gold" },
  { id: "118", text: "Every strike brings me closer to the next home run.", author: "Bruce Lee", style: "frost" },
  { id: "119", text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Ada Lovelace", style: "magma" },
  { id: "120", text: "The only way to do great work is to love what you do.", author: "Elon Musk", style: "frost" },
  { id: "121", text: "Focus is a matter of deciding what things you're not going to do.", author: "Socrates", style: "glitch" },
  { id: "122", text: "The best way to predict the future is to invent it.", author: "Isaac Newton", style: "biohazard" },
  { id: "123", text: "Stay hungry, stay foolish.", author: "Sun Tzu", style: "retro" },
  { id: "124", text: "You miss 100% of the shots you don't take.", author: "Sun Tzu", style: "cyberpunk" },
  { id: "125", text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Michael Jordan", style: "glitch" },
  { id: "126", text: "Talent wins games, but teamwork and intelligence win championships.", author: "Socrates", style: "cosmic" },
  { id: "127", text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Socrates", style: "glitch" },
  { id: "128", text: "I've failed over and over and over again in my life. And that is why I succeed.", author: "Richard Feynman", style: "cyberpunk" },
  { id: "129", text: "If you're afraid to fail, then you're probably going to fail.", author: "Epictetus", style: "retro" },
  { id: "130", text: "Don't count the days, make the days count.", author: "John von Neumann", style: "synthwave" },
  { id: "131", text: "Float like a butterfly, sting like a bee.", author: "Alan Turing", style: "cyberpunk" },
  { id: "132", text: "The fight is won or lost far away from witnesses.", author: "John von Neumann", style: "brutalist" },
  { id: "133", text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Seneca", style: "hologram" },
  { id: "134", text: "It's hard to beat a person who never gives up.", author: "Leonhard Euler", style: "comic" },
  { id: "135", text: "Quality is not an act, it is a habit.", author: "David Goggins", style: "hologram" },
  { id: "136", text: "Well done is better than well said.", author: "Aristotle", style: "frost" },
  { id: "137", text: "The secret of getting ahead is getting started.", author: "Bruce Lee", style: "cosmic" },
  { id: "138", text: "It does not matter how slowly you go as long as you do not stop.", author: "Carl Friedrich Gauss", style: "cyberpunk" },
  { id: "139", text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Aristotle", style: "cosmic" },
  { id: "140", text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Paul Graham", style: "comic" },
  { id: "141", text: "No man has the right to be an amateur in the matter of physical training.", author: "Albert Einstein", style: "frost" },
  { id: "142", text: "Be intolerant of your own ignorance.", author: "Ada Lovelace", style: "synthwave" },
  { id: "143", text: "First, master the fundamentals.", author: "Marcus Aurelius", style: "minimal" },
  { id: "144", text: "Knowledge speaks, but wisdom listens.", author: "Kobe Bryant", style: "retro" },
  { id: "145", text: "The mind is everything. What you think you become.", author: "David Goggins", style: "magma" },
  { id: "146", text: "The unexamined life is not worth living.", author: "Sun Tzu", style: "cyberpunk" },
  { id: "147", text: "Happiness depends upon ourselves.", author: "Epictetus", style: "neon" },
  { id: "148", text: "Nature does nothing in vain.", author: "Aristotle", style: "synthwave" },
  { id: "149", text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", style: "gold" },
  { id: "150", text: "The only true wisdom is in knowing you know nothing.", author: "Alan Turing", style: "hologram" },
  { id: "151", text: "There is no genius without some touch of madness.", author: "Michael Jordan", style: "glitch" },
  { id: "152", text: "Great acts are made up of small deeds.", author: "Paul Graham", style: "gold" },
  { id: "153", text: "Learning never exhausts the mind.", author: "Sun Tzu", style: "comic" },
  { id: "154", text: "Nothing is impossible for him who will try.", author: "David Goggins", style: "retro" },
  { id: "155", text: "The roots of education are bitter, but the fruit is sweet.", author: "Bruce Lee", style: "biohazard" },
  { id: "156", text: "The energy of the mind is the essence of life.", author: "Aristotle", style: "glassmorphism" },
  { id: "157", text: "He who has overcome his fears will truly be free.", author: "Leonhard Euler", style: "cosmic" },
  { id: "158", text: "We make war that we may live in peace.", author: "Socrates", style: "synthwave" },
  { id: "159", text: "Courage is the first of human qualities because it is the quality which guarantees the others.", author: "Naval Ravikant", style: "cosmic" },
  { id: "160", text: "Difficulties strengthen the mind, as labor does the body.", author: "David Goggins", style: "gold" },
  { id: "161", text: "A journey of a thousand miles begins with a single step.", author: "Sam Altman", style: "retro" },
  { id: "162", text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Ada Lovelace", style: "minimal" },
  { id: "163", text: "Mastering others is strength; mastering yourself is true power.", author: "Epictetus", style: "neon" },
  { id: "164", text: "The best fighter is never angry.", author: "Socrates", style: "neon" },
  { id: "165", text: "When you are content to be simply yourself and don't compare or compete, everybody will respect you.", author: "Kobe Bryant", style: "cyberpunk" },
  { id: "166", text: "Anticipate the difficult by managing the easy.", author: "Epictetus", style: "neon" },
  { id: "167", text: "To lead people walk behind them.", author: "Aristotle", style: "hologram" },
  { id: "168", text: "Silence is a source of great strength.", author: "Kobe Bryant", style: "hologram" },
  { id: "169", text: "He who knows, does not speak. He who speaks, does not know.", author: "Kobe Bryant", style: "glassmorphism" },
  { id: "170", text: "The wise man does not lay up his own treasures. The more he gives to others, the more he has for his own.", author: "Paul Graham", style: "gold" },
  { id: "171", text: "Life is a series of natural and spontaneous changes.", author: "Albert Einstein", style: "neon" },
  { id: "172", text: "Act without expectation.", author: "Steve Jobs", style: "neon" },
  { id: "173", text: "Care about what other people think and you will always be their prisoner.", author: "Kobe Bryant", style: "brutalist" },
  { id: "174", text: "Nature does not hurry, yet everything is accomplished.", author: "Ada Lovelace", style: "hologram" },
  { id: "175", text: "Do the difficult things while they are easy and do the great things while they are small.", author: "Isaac Newton", style: "gold" },
  { id: "176", text: "If you correct your mind, the rest of your life will fall into place.", author: "John von Neumann", style: "retro" },
  { id: "177", text: "The softest things in the world overcome the hardest things in the world.", author: "Alan Turing", style: "glitch" },
  { id: "178", text: "Those who know do not speak. Those who speak do not know.", author: "Bruce Lee", style: "neon" },
  { id: "179", text: "A good traveler has no fixed plans and is not intent on arriving.", author: "John von Neumann", style: "glitch" },
  { id: "180", text: "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.", author: "Epictetus", style: "glitch" },
  { id: "181", text: "Be still like a mountain and flow like a great river.", author: "Epictetus", style: "brutalist" },
  { id: "182", text: "Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend.", author: "Paul Graham", style: "cyberpunk" },
  { id: "183", text: "Simplicity is the ultimate sophistication.", author: "Leonhard Euler", style: "neon" },
  { id: "184", text: "Art is never finished, only abandoned.", author: "Seneca", style: "cosmic" },
  { id: "185", text: "Where the spirit does not work with the hand, there is no art.", author: "Seneca", style: "hologram" },
  { id: "186", text: "Tears come from the heart and not from the brain.", author: "Paul Graham", style: "glassmorphism" },
  { id: "187", text: "As a well-spent day brings happy sleep, so a life well spent brings happy death.", author: "Paul Graham", style: "cyberpunk" },
  { id: "188", text: "The greatest deception men suffer is from their own opinions.", author: "Richard Feynman", style: "minimal" },
  { id: "189", text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.", author: "Socrates", style: "minimal" },
  { id: "190", text: "Nothing can be loved or hated unless it is first understood.", author: "Naval Ravikant", style: "magma" },
  { id: "191", text: "Experience never errs; it is only your judgments that err.", author: "Michael Jordan", style: "retro" },
  { id: "192", text: "He who loves practice without theory is like the sailor who boards ship without a rudder and compass.", author: "Paul Graham", style: "retro" },
  { id: "193", text: "While I thought that I was learning how to live, I have been learning how to die.", author: "Epictetus", style: "glassmorphism" },
  { id: "194", text: "Intellectual passion drives out sensuality.", author: "Aristotle", style: "magma" },
  { id: "195", text: "All our knowledge has its origins in our perceptions.", author: "Kobe Bryant", style: "hologram" },
  { id: "196", text: "Iron rusts from disuse; water loses its purity from stagnation... even so does inaction sap the vigor of the mind.", author: "Marcus Aurelius", style: "hologram" },
  { id: "197", text: "Make your work to be in keeping with your purpose.", author: "David Goggins", style: "synthwave" },
  { id: "198", text: "The truth of things is the chief nutriment of superior intellects.", author: "Naval Ravikant", style: "glitch" },
  { id: "199", text: "A beautiful body perishes, but a work of art dies not.", author: "Alan Turing", style: "hologram" },
  { id: "200", text: "The difference between a master and a beginner is that the master has failed more times than the beginner has even tried.", author: "Elon Musk", style: "cosmic" },
  { id: "201", text: "A flawless run isn't luck. It's a thousand invisible mistakes corrected.", author: "Alan Turing", style: "retro" },
  { id: "202", text: "Precision beats power. Timing beats speed.", author: "Isaac Newton", style: "frost" },
  { id: "203", text: "The obstacle is the way.", author: "Carl Friedrich Gauss", style: "frost" },
  { id: "204", text: "What stands in the way becomes the way.", author: "Socrates", style: "frost" },
  { id: "205", text: "You have power over your mind - not outside events.", author: "Ada Lovelace", style: "gold" },
  { id: "206", text: "The more you sweat in practice, the less you bleed in battle.", author: "Miyamoto Musashi", style: "gold" },
  { id: "207", text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "David Goggins", style: "gold" },
  { id: "208", text: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", author: "Sam Altman", style: "gold" },
  { id: "209", text: "There is no elevator to success, you have to take the stairs.", author: "Isaac Newton", style: "retro" },
  { id: "210", text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Aristotle", style: "brutalist" },
  { id: "211", text: "In the middle of difficulty lies opportunity.", author: "Aristotle", style: "magma" },
  { id: "212", text: "Pure mathematics is, in its way, the poetry of logical ideas.", author: "Paul Graham", style: "biohazard" },
  { id: "213", text: "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.", author: "Marcus Aurelius", style: "hologram" },
  { id: "214", text: "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is.", author: "Carl Friedrich Gauss", style: "magma" },
  { id: "215", text: "The essence of mathematics is not to make simple things complicated, but to make complicated things simple.", author: "Richard Feynman", style: "minimal" },
  { id: "216", text: "Genius is 1% talent and 99% hard work.", author: "David Goggins", style: "comic" },
  { id: "217", text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Steve Jobs", style: "glitch" },
  { id: "218", text: "Every strike brings me closer to the next home run.", author: "Socrates", style: "magma" },
  { id: "219", text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Michael Jordan", style: "glassmorphism" },
  { id: "220", text: "The only way to do great work is to love what you do.", author: "Kobe Bryant", style: "retro" },
  { id: "221", text: "Focus is a matter of deciding what things you're not going to do.", author: "Miyamoto Musashi", style: "cosmic" },
  { id: "222", text: "The best way to predict the future is to invent it.", author: "Socrates", style: "synthwave" },
  { id: "223", text: "Stay hungry, stay foolish.", author: "Elon Musk", style: "cyberpunk" },
  { id: "224", text: "You miss 100% of the shots you don't take.", author: "Albert Einstein", style: "gold" },
  { id: "225", text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Paul Graham", style: "frost" },
  { id: "226", text: "Talent wins games, but teamwork and intelligence win championships.", author: "Richard Feynman", style: "glitch" },
  { id: "227", text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Elon Musk", style: "magma" },
  { id: "228", text: "I've failed over and over and over again in my life. And that is why I succeed.", author: "Ada Lovelace", style: "hologram" },
  { id: "229", text: "If you're afraid to fail, then you're probably going to fail.", author: "Albert Einstein", style: "glitch" },
  { id: "230", text: "Don't count the days, make the days count.", author: "Paul Graham", style: "glitch" },
  { id: "231", text: "Float like a butterfly, sting like a bee.", author: "Leonhard Euler", style: "cosmic" },
  { id: "232", text: "The fight is won or lost far away from witnesses.", author: "Paul Graham", style: "biohazard" },
  { id: "233", text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Albert Einstein", style: "frost" },
  { id: "234", text: "It's hard to beat a person who never gives up.", author: "Ada Lovelace", style: "comic" },
  { id: "235", text: "Quality is not an act, it is a habit.", author: "Kobe Bryant", style: "glitch" },
  { id: "236", text: "Well done is better than well said.", author: "Paul Graham", style: "synthwave" },
  { id: "237", text: "The secret of getting ahead is getting started.", author: "Sam Altman", style: "biohazard" },
  { id: "238", text: "It does not matter how slowly you go as long as you do not stop.", author: "Steve Jobs", style: "brutalist" },
  { id: "239", text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Aristotle", style: "synthwave" },
  { id: "240", text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Naval Ravikant", style: "brutalist" },
  { id: "241", text: "No man has the right to be an amateur in the matter of physical training.", author: "Carl Friedrich Gauss", style: "frost" },
  { id: "242", text: "Be intolerant of your own ignorance.", author: "Elon Musk", style: "retro" },
  { id: "243", text: "First, master the fundamentals.", author: "Steve Jobs", style: "frost" },
  { id: "244", text: "Knowledge speaks, but wisdom listens.", author: "Miyamoto Musashi", style: "glitch" },
  { id: "245", text: "The mind is everything. What you think you become.", author: "Paul Graham", style: "magma" },
  { id: "246", text: "The unexamined life is not worth living.", author: "Epictetus", style: "neon" },
  { id: "247", text: "Happiness depends upon ourselves.", author: "Bruce Lee", style: "biohazard" },
  { id: "248", text: "Nature does nothing in vain.", author: "Sam Altman", style: "comic" },
  { id: "249", text: "Patience is bitter, but its fruit is sweet.", author: "Elon Musk", style: "retro" },
  { id: "250", text: "The only true wisdom is in knowing you know nothing.", author: "Naval Ravikant", style: "frost" },
  { id: "251", text: "There is no genius without some touch of madness.", author: "Seneca", style: "magma" },
  { id: "252", text: "Great acts are made up of small deeds.", author: "Seneca", style: "brutalist" },
  { id: "253", text: "Learning never exhausts the mind.", author: "Kobe Bryant", style: "comic" },
  { id: "254", text: "Nothing is impossible for him who will try.", author: "Marcus Aurelius", style: "cyberpunk" },
  { id: "255", text: "The roots of education are bitter, but the fruit is sweet.", author: "Sam Altman", style: "magma" },
  { id: "256", text: "The energy of the mind is the essence of life.", author: "Seneca", style: "hologram" },
  { id: "257", text: "He who has overcome his fears will truly be free.", author: "Epictetus", style: "frost" },
  { id: "258", text: "We make war that we may live in peace.", author: "Carl Friedrich Gauss", style: "cosmic" },
  { id: "259", text: "Courage is the first of human qualities because it is the quality which guarantees the others.", author: "Alan Turing", style: "comic" },
  { id: "260", text: "Difficulties strengthen the mind, as labor does the body.", author: "Carl Friedrich Gauss", style: "synthwave" },
  { id: "261", text: "A journey of a thousand miles begins with a single step.", author: "Carl Friedrich Gauss", style: "hologram" },
  { id: "262", text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Sam Altman", style: "minimal" },
  { id: "263", text: "Mastering others is strength; mastering yourself is true power.", author: "Steve Jobs", style: "glassmorphism" },
  { id: "264", text: "The best fighter is never angry.", author: "Carl Friedrich Gauss", style: "synthwave" },
  { id: "265", text: "When you are content to be simply yourself and don't compare or compete, everybody will respect you.", author: "Miyamoto Musashi", style: "synthwave" },
  { id: "266", text: "Anticipate the difficult by managing the easy.", author: "Marcus Aurelius", style: "frost" },
  { id: "267", text: "To lead people walk behind them.", author: "Kobe Bryant", style: "hologram" },
  { id: "268", text: "Silence is a source of great strength.", author: "John von Neumann", style: "biohazard" },
  { id: "269", text: "He who knows, does not speak. He who speaks, does not know.", author: "Sam Altman", style: "cosmic" },
  { id: "270", text: "The wise man does not lay up his own treasures. The more he gives to others, the more he has for his own.", author: "Sun Tzu", style: "comic" },
  { id: "271", text: "Life is a series of natural and spontaneous changes.", author: "Aristotle", style: "hologram" },
  { id: "272", text: "Act without expectation.", author: "Albert Einstein", style: "neon" },
  { id: "273", text: "Care about what other people think and you will always be their prisoner.", author: "Sam Altman", style: "hologram" },
  { id: "274", text: "Nature does not hurry, yet everything is accomplished.", author: "David Goggins", style: "retro" },
  { id: "275", text: "Do the difficult things while they are easy and do the great things while they are small.", author: "Sam Altman", style: "cyberpunk" },
  { id: "276", text: "If you correct your mind, the rest of your life will fall into place.", author: "Kobe Bryant", style: "minimal" },
  { id: "277", text: "The softest things in the world overcome the hardest things in the world.", author: "Leonhard Euler", style: "cyberpunk" },
  { id: "278", text: "Those who know do not speak. Those who speak do not know.", author: "Seneca", style: "retro" },
  { id: "279", text: "A good traveler has no fixed plans and is not intent on arriving.", author: "Michael Jordan", style: "minimal" },
  { id: "280", text: "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.", author: "Alan Turing", style: "comic" },
  { id: "281", text: "Be still like a mountain and flow like a great river.", author: "Paul Graham", style: "comic" },
  { id: "282", text: "Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend.", author: "Sam Altman", style: "gold" },
  { id: "283", text: "Simplicity is the ultimate sophistication.", author: "Elon Musk", style: "minimal" },
  { id: "284", text: "Art is never finished, only abandoned.", author: "Socrates", style: "minimal" },
  { id: "285", text: "Where the spirit does not work with the hand, there is no art.", author: "Albert Einstein", style: "cyberpunk" },
  { id: "286", text: "Tears come from the heart and not from the brain.", author: "John von Neumann", style: "glitch" },
  { id: "287", text: "As a well-spent day brings happy sleep, so a life well spent brings happy death.", author: "Seneca", style: "minimal" },
  { id: "288", text: "The greatest deception men suffer is from their own opinions.", author: "Richard Feynman", style: "magma" },
  { id: "289", text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.", author: "Socrates", style: "frost" },
  { id: "290", text: "Nothing can be loved or hated unless it is first understood.", author: "Socrates", style: "frost" },
  { id: "291", text: "Experience never errs; it is only your judgments that err.", author: "Paul Graham", style: "cosmic" },
  { id: "292", text: "He who loves practice without theory is like the sailor who boards ship without a rudder and compass.", author: "Seneca", style: "glitch" },
  { id: "293", text: "While I thought that I was learning how to live, I have been learning how to die.", author: "David Goggins", style: "synthwave" },
  { id: "294", text: "Intellectual passion drives out sensuality.", author: "John von Neumann", style: "gold" },
  { id: "295", text: "All our knowledge has its origins in our perceptions.", author: "Marcus Aurelius", style: "gold" },
  { id: "296", text: "Iron rusts from disuse; water loses its purity from stagnation... even so does inaction sap the vigor of the mind.", author: "Socrates", style: "gold" },
  { id: "297", text: "Make your work to be in keeping with your purpose.", author: "Steve Jobs", style: "brutalist" },
  { id: "298", text: "The truth of things is the chief nutriment of superior intellects.", author: "Bruce Lee", style: "frost" },
  { id: "299", text: "A beautiful body perishes, but a work of art dies not.", author: "Carl Friedrich Gauss", style: "synthwave" },
  { id: "300", text: "The difference between a master and a beginner is that the master has failed more times than the beginner has even tried.", author: "Miyamoto Musashi", style: "glassmorphism" },
  { id: "301", text: "A flawless run isn't luck. It's a thousand invisible mistakes corrected.", author: "Paul Graham", style: "magma" },
  { id: "302", text: "Precision beats power. Timing beats speed.", author: "Miyamoto Musashi", style: "brutalist" },
  { id: "303", text: "The obstacle is the way.", author: "Marcus Aurelius", style: "glassmorphism" },
  { id: "304", text: "What stands in the way becomes the way.", author: "Bruce Lee", style: "comic" },
  { id: "305", text: "You have power over your mind - not outside events.", author: "Albert Einstein", style: "retro" },
  { id: "306", text: "The more you sweat in practice, the less you bleed in battle.", author: "Sun Tzu", style: "synthwave" },
  { id: "307", text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Michael Jordan", style: "brutalist" },
  { id: "308", text: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", author: "Sam Altman", style: "cosmic" },
  { id: "309", text: "There is no elevator to success, you have to take the stairs.", author: "John von Neumann", style: "hologram" },
  { id: "310", text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Miyamoto Musashi", style: "comic" },
  { id: "311", text: "In the middle of difficulty lies opportunity.", author: "Richard Feynman", style: "brutalist" },
  { id: "312", text: "Pure mathematics is, in its way, the poetry of logical ideas.", author: "Michael Jordan", style: "gold" },
  { id: "313", text: "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.", author: "David Goggins", style: "cosmic" },
  { id: "314", text: "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is.", author: "Naval Ravikant", style: "glitch" },
  { id: "315", text: "The essence of mathematics is not to make simple things complicated, but to make complicated things simple.", author: "Ada Lovelace", style: "glitch" },
  { id: "316", text: "Genius is 1% talent and 99% hard work.", author: "Miyamoto Musashi", style: "brutalist" },
  { id: "317", text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Michael Jordan", style: "comic" },
  { id: "318", text: "Every strike brings me closer to the next home run.", author: "Carl Friedrich Gauss", style: "cyberpunk" },
  { id: "319", text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Alan Turing", style: "biohazard" },
  { id: "320", text: "The only way to do great work is to love what you do.", author: "Richard Feynman", style: "retro" },
  { id: "321", text: "Focus is a matter of deciding what things you're not going to do.", author: "Paul Graham", style: "brutalist" },
  { id: "322", text: "The best way to predict the future is to invent it.", author: "Miyamoto Musashi", style: "synthwave" },
  { id: "323", text: "Stay hungry, stay foolish.", author: "Epictetus", style: "retro" },
  { id: "324", text: "You miss 100% of the shots you don't take.", author: "Bruce Lee", style: "comic" },
  { id: "325", text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Alan Turing", style: "magma" },
  { id: "326", text: "Talent wins games, but teamwork and intelligence win championships.", author: "Naval Ravikant", style: "glassmorphism" },
  { id: "327", text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Bruce Lee", style: "cosmic" },
  { id: "328", text: "I've failed over and over and over again in my life. And that is why I succeed.", author: "Albert Einstein", style: "brutalist" },
  { id: "329", text: "If you're afraid to fail, then you're probably going to fail.", author: "Aristotle", style: "comic" },
  { id: "330", text: "Don't count the days, make the days count.", author: "Aristotle", style: "glassmorphism" },
  { id: "331", text: "Float like a butterfly, sting like a bee.", author: "Steve Jobs", style: "frost" },
  { id: "332", text: "The fight is won or lost far away from witnesses.", author: "Richard Feynman", style: "synthwave" },
  { id: "333", text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Sun Tzu", style: "biohazard" },
  { id: "334", text: "It's hard to beat a person who never gives up.", author: "Naval Ravikant", style: "cyberpunk" },
  { id: "335", text: "Quality is not an act, it is a habit.", author: "John von Neumann", style: "cosmic" },
  { id: "336", text: "Well done is better than well said.", author: "Michael Jordan", style: "cyberpunk" },
  { id: "337", text: "The secret of getting ahead is getting started.", author: "Bruce Lee", style: "magma" },
  { id: "338", text: "It does not matter how slowly you go as long as you do not stop.", author: "Ada Lovelace", style: "synthwave" },
  { id: "339", text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Sun Tzu", style: "minimal" },
  { id: "340", text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", style: "glassmorphism" },
  { id: "341", text: "No man has the right to be an amateur in the matter of physical training.", author: "Epictetus", style: "brutalist" },
  { id: "342", text: "Be intolerant of your own ignorance.", author: "Kobe Bryant", style: "brutalist" },
  { id: "343", text: "First, master the fundamentals.", author: "Naval Ravikant", style: "gold" },
  { id: "344", text: "Knowledge speaks, but wisdom listens.", author: "Isaac Newton", style: "frost" },
  { id: "345", text: "The mind is everything. What you think you become.", author: "Paul Graham", style: "brutalist" },
  { id: "346", text: "The unexamined life is not worth living.", author: "Alan Turing", style: "brutalist" },
  { id: "347", text: "Happiness depends upon ourselves.", author: "Paul Graham", style: "comic" },
  { id: "348", text: "Nature does nothing in vain.", author: "Seneca", style: "retro" },
  { id: "349", text: "Patience is bitter, but its fruit is sweet.", author: "Socrates", style: "magma" },
  { id: "350", text: "The only true wisdom is in knowing you know nothing.", author: "Sam Altman", style: "biohazard" },
  { id: "351", text: "There is no genius without some touch of madness.", author: "David Goggins", style: "hologram" },
  { id: "352", text: "Great acts are made up of small deeds.", author: "Socrates", style: "synthwave" },
  { id: "353", text: "Learning never exhausts the mind.", author: "Sam Altman", style: "glassmorphism" },
  { id: "354", text: "Nothing is impossible for him who will try.", author: "Kobe Bryant", style: "frost" },
  { id: "355", text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", style: "brutalist" },
  { id: "356", text: "The energy of the mind is the essence of life.", author: "Sam Altman", style: "synthwave" },
  { id: "357", text: "He who has overcome his fears will truly be free.", author: "David Goggins", style: "glitch" },
  { id: "358", text: "We make war that we may live in peace.", author: "Carl Friedrich Gauss", style: "cyberpunk" },
  { id: "359", text: "Courage is the first of human qualities because it is the quality which guarantees the others.", author: "Kobe Bryant", style: "hologram" },
  { id: "360", text: "Difficulties strengthen the mind, as labor does the body.", author: "Marcus Aurelius", style: "biohazard" },
  { id: "361", text: "A journey of a thousand miles begins with a single step.", author: "Albert Einstein", style: "glassmorphism" },
  { id: "362", text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Miyamoto Musashi", style: "retro" },
  { id: "363", text: "Mastering others is strength; mastering yourself is true power.", author: "Seneca", style: "magma" },
  { id: "364", text: "The best fighter is never angry.", author: "Richard Feynman", style: "cyberpunk" },
  { id: "365", text: "When you are content to be simply yourself and don't compare or compete, everybody will respect you.", author: "Sam Altman", style: "glassmorphism" },
  { id: "366", text: "Anticipate the difficult by managing the easy.", author: "Seneca", style: "cosmic" },
  { id: "367", text: "To lead people walk behind them.", author: "David Goggins", style: "gold" },
  { id: "368", text: "Silence is a source of great strength.", author: "Steve Jobs", style: "synthwave" },
  { id: "369", text: "He who knows, does not speak. He who speaks, does not know.", author: "Albert Einstein", style: "minimal" },
  { id: "370", text: "The wise man does not lay up his own treasures. The more he gives to others, the more he has for his own.", author: "Socrates", style: "comic" },
  { id: "371", text: "Life is a series of natural and spontaneous changes.", author: "Elon Musk", style: "gold" },
  { id: "372", text: "Act without expectation.", author: "Alan Turing", style: "cosmic" },
  { id: "373", text: "Care about what other people think and you will always be their prisoner.", author: "John von Neumann", style: "synthwave" },
  { id: "374", text: "Nature does not hurry, yet everything is accomplished.", author: "Michael Jordan", style: "gold" },
  { id: "375", text: "Do the difficult things while they are easy and do the great things while they are small.", author: "Steve Jobs", style: "brutalist" },
  { id: "376", text: "If you correct your mind, the rest of your life will fall into place.", author: "Kobe Bryant", style: "brutalist" },
  { id: "377", text: "The softest things in the world overcome the hardest things in the world.", author: "Albert Einstein", style: "cyberpunk" },
  { id: "378", text: "Those who know do not speak. Those who speak do not know.", author: "Elon Musk", style: "glitch" },
  { id: "379", text: "A good traveler has no fixed plans and is not intent on arriving.", author: "Socrates", style: "cyberpunk" },
  { id: "380", text: "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.", author: "Elon Musk", style: "glassmorphism" },
  { id: "381", text: "Be still like a mountain and flow like a great river.", author: "Ada Lovelace", style: "frost" },
  { id: "382", text: "Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend.", author: "Aristotle", style: "cosmic" },
  { id: "383", text: "Simplicity is the ultimate sophistication.", author: "John von Neumann", style: "synthwave" },
  { id: "384", text: "Art is never finished, only abandoned.", author: "Carl Friedrich Gauss", style: "comic" },
  { id: "385", text: "Where the spirit does not work with the hand, there is no art.", author: "Sun Tzu", style: "magma" },
  { id: "386", text: "Tears come from the heart and not from the brain.", author: "Marcus Aurelius", style: "magma" },
  { id: "387", text: "As a well-spent day brings happy sleep, so a life well spent brings happy death.", author: "Marcus Aurelius", style: "biohazard" },
  { id: "388", text: "The greatest deception men suffer is from their own opinions.", author: "Steve Jobs", style: "glitch" },
  { id: "389", text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.", author: "Leonhard Euler", style: "gold" },
  { id: "390", text: "Nothing can be loved or hated unless it is first understood.", author: "Paul Graham", style: "comic" },
  { id: "391", text: "Experience never errs; it is only your judgments that err.", author: "Sun Tzu", style: "cosmic" },
  { id: "392", text: "He who loves practice without theory is like the sailor who boards ship without a rudder and compass.", author: "Sam Altman", style: "biohazard" },
  { id: "393", text: "While I thought that I was learning how to live, I have been learning how to die.", author: "Paul Graham", style: "retro" },
  { id: "394", text: "Intellectual passion drives out sensuality.", author: "Elon Musk", style: "gold" },
  { id: "395", text: "All our knowledge has its origins in our perceptions.", author: "Seneca", style: "comic" },
  { id: "396", text: "Iron rusts from disuse; water loses its purity from stagnation... even so does inaction sap the vigor of the mind.", author: "Steve Jobs", style: "glassmorphism" },
  { id: "397", text: "Make your work to be in keeping with your purpose.", author: "Leonhard Euler", style: "biohazard" },
  { id: "398", text: "The truth of things is the chief nutriment of superior intellects.", author: "David Goggins", style: "gold" },
  { id: "399", text: "A beautiful body perishes, but a work of art dies not.", author: "Isaac Newton", style: "gold" },
  { id: "400", text: "In the architecture of mind, the apex scholar finds clarity in the noise.", author: "Apex Intelligence", style: "glitch" },
  { id: "401", text: "When variables align, the silent observer calculates the perfect victory.", author: "Apex Intelligence", style: "frost" },
  { id: "402", text: "In the architecture of mind, the apex scholar rewrites the rules of the game.", author: "Apex Intelligence", style: "neon" },
  { id: "403", text: "To conquer the unknown, the relentless student finds clarity in the noise.", author: "Apex Intelligence", style: "retro" },
  { id: "404", text: "Through relentless focus, the apex scholar calculates the perfect victory.", author: "Apex Intelligence", style: "glitch" },
  { id: "405", text: "In the architecture of mind, the relentless student turns failure into data.", author: "Apex Intelligence", style: "glitch" },
  { id: "406", text: "Through relentless focus, a true master rewrites the rules of the game.", author: "Apex Intelligence", style: "minimal" },
  { id: "407", text: "Against impossible odds, the relentless student turns failure into data.", author: "Apex Intelligence", style: "neon" },
  { id: "408", text: "In the arena of logic, a true master turns failure into data.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "409", text: "To conquer the unknown, the apex scholar sees what others miss.", author: "Apex Intelligence", style: "gold" },
  { id: "410", text: "In the arena of logic, a calculated mind finds clarity in the noise.", author: "Apex Intelligence", style: "magma" },
  { id: "411", text: "To conquer the unknown, the relentless student finds clarity in the noise.", author: "Apex Intelligence", style: "magma" },
  { id: "412", text: "In the architecture of mind, the silent observer turns failure into data.", author: "Apex Intelligence", style: "hologram" },
  { id: "413", text: "Through relentless focus, the architect of fate strikes with absolute precision.", author: "Apex Intelligence", style: "comic" },
  { id: "414", text: "When variables align, a true master strikes with absolute precision.", author: "Apex Intelligence", style: "comic" },
  { id: "415", text: "In the arena of logic, the apex scholar sees what others miss.", author: "Apex Intelligence", style: "biohazard" },
  { id: "416", text: "In the architecture of mind, the relentless student sees what others miss.", author: "Apex Intelligence", style: "retro" },
  { id: "417", text: "Against impossible odds, the silent observer turns failure into data.", author: "Apex Intelligence", style: "minimal" },
  { id: "418", text: "Through relentless focus, a true master strikes with absolute precision.", author: "Apex Intelligence", style: "comic" },
  { id: "419", text: "In the architecture of mind, a true master strikes with absolute precision.", author: "Apex Intelligence", style: "neon" },
  { id: "420", text: "Where chaos meets order, the apex scholar sees what others miss.", author: "Apex Intelligence", style: "hologram" },
  { id: "421", text: "When variables align, the silent observer finds clarity in the noise.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "422", text: "In the architecture of mind, the architect of fate calculates the perfect victory.", author: "Apex Intelligence", style: "glitch" },
  { id: "423", text: "To conquer the unknown, a true master rewrites the rules of the game.", author: "Apex Intelligence", style: "frost" },
  { id: "424", text: "Where chaos meets order, the silent observer strikes with absolute precision.", author: "Apex Intelligence", style: "cosmic" },
  { id: "425", text: "Where chaos meets order, the architect of fate calculates the perfect victory.", author: "Apex Intelligence", style: "comic" },
  { id: "426", text: "Against impossible odds, the architect of fate turns failure into data.", author: "Apex Intelligence", style: "hologram" },
  { id: "427", text: "When variables align, a calculated mind sees what others miss.", author: "Apex Intelligence", style: "gold" },
  { id: "428", text: "In the architecture of mind, a calculated mind calculates the perfect victory.", author: "Apex Intelligence", style: "brutalist" },
  { id: "429", text: "Through relentless focus, a calculated mind turns failure into data.", author: "Apex Intelligence", style: "comic" },
  { id: "430", text: "Beyond the infinite, the apex scholar sees what others miss.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "431", text: "In the architecture of mind, the silent observer calculates the perfect victory.", author: "Apex Intelligence", style: "glitch" },
  { id: "432", text: "When variables align, the apex scholar strikes with absolute precision.", author: "Apex Intelligence", style: "biohazard" },
  { id: "433", text: "Against impossible odds, the silent observer calculates the perfect victory.", author: "Apex Intelligence", style: "hologram" },
  { id: "434", text: "To conquer the unknown, the relentless student turns failure into data.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "435", text: "Beyond the infinite, the relentless student strikes with absolute precision.", author: "Apex Intelligence", style: "cosmic" },
  { id: "436", text: "In the arena of logic, a calculated mind turns failure into data.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "437", text: "When variables align, a true master calculates the perfect victory.", author: "Apex Intelligence", style: "minimal" },
  { id: "438", text: "To conquer the unknown, the architect of fate calculates the perfect victory.", author: "Apex Intelligence", style: "neon" },
  { id: "439", text: "Beyond the infinite, the apex scholar turns failure into data.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "440", text: "When variables align, the apex scholar rewrites the rules of the game.", author: "Apex Intelligence", style: "frost" },
  { id: "441", text: "Against impossible odds, a true master strikes with absolute precision.", author: "Apex Intelligence", style: "magma" },
  { id: "442", text: "In the arena of logic, a calculated mind strikes with absolute precision.", author: "Apex Intelligence", style: "frost" },
  { id: "443", text: "Beyond the infinite, the relentless student finds clarity in the noise.", author: "Apex Intelligence", style: "hologram" },
  { id: "444", text: "To conquer the unknown, the relentless student turns failure into data.", author: "Apex Intelligence", style: "synthwave" },
  { id: "445", text: "In the arena of logic, a true master rewrites the rules of the game.", author: "Apex Intelligence", style: "frost" },
  { id: "446", text: "In the arena of logic, the relentless student rewrites the rules of the game.", author: "Apex Intelligence", style: "minimal" },
  { id: "447", text: "Through relentless focus, the architect of fate turns failure into data.", author: "Apex Intelligence", style: "brutalist" },
  { id: "448", text: "Where chaos meets order, a calculated mind turns failure into data.", author: "Apex Intelligence", style: "retro" },
  { id: "449", text: "Where chaos meets order, the relentless student sees what others miss.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "450", text: "In the architecture of mind, the apex scholar rewrites the rules of the game.", author: "Apex Intelligence", style: "minimal" },
  { id: "451", text: "To conquer the unknown, the relentless student rewrites the rules of the game.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "452", text: "Against impossible odds, the silent observer rewrites the rules of the game.", author: "Apex Intelligence", style: "cosmic" },
  { id: "453", text: "When variables align, the apex scholar turns failure into data.", author: "Apex Intelligence", style: "hologram" },
  { id: "454", text: "Beyond the infinite, the silent observer turns failure into data.", author: "Apex Intelligence", style: "retro" },
  { id: "455", text: "Beyond the infinite, the relentless student turns failure into data.", author: "Apex Intelligence", style: "hologram" },
  { id: "456", text: "In the arena of logic, a calculated mind sees what others miss.", author: "Apex Intelligence", style: "comic" },
  { id: "457", text: "In the arena of logic, a true master calculates the perfect victory.", author: "Apex Intelligence", style: "hologram" },
  { id: "458", text: "Against impossible odds, the relentless student turns failure into data.", author: "Apex Intelligence", style: "magma" },
  { id: "459", text: "Beyond the infinite, the architect of fate finds clarity in the noise.", author: "Apex Intelligence", style: "comic" },
  { id: "460", text: "In the arena of logic, the architect of fate calculates the perfect victory.", author: "Apex Intelligence", style: "retro" },
  { id: "461", text: "In the arena of logic, the relentless student calculates the perfect victory.", author: "Apex Intelligence", style: "frost" },
  { id: "462", text: "Through relentless focus, the architect of fate calculates the perfect victory.", author: "Apex Intelligence", style: "biohazard" },
  { id: "463", text: "In the architecture of mind, a calculated mind strikes with absolute precision.", author: "Apex Intelligence", style: "cosmic" },
  { id: "464", text: "In the arena of logic, a calculated mind rewrites the rules of the game.", author: "Apex Intelligence", style: "retro" },
  { id: "465", text: "Through relentless focus, the silent observer finds clarity in the noise.", author: "Apex Intelligence", style: "retro" },
  { id: "466", text: "In the arena of logic, the architect of fate calculates the perfect victory.", author: "Apex Intelligence", style: "minimal" },
  { id: "467", text: "Where chaos meets order, the relentless student calculates the perfect victory.", author: "Apex Intelligence", style: "brutalist" },
  { id: "468", text: "Against impossible odds, the relentless student finds clarity in the noise.", author: "Apex Intelligence", style: "frost" },
  { id: "469", text: "In the architecture of mind, the apex scholar strikes with absolute precision.", author: "Apex Intelligence", style: "frost" },
  { id: "470", text: "In the arena of logic, the apex scholar strikes with absolute precision.", author: "Apex Intelligence", style: "gold" },
  { id: "471", text: "Through relentless focus, the relentless student calculates the perfect victory.", author: "Apex Intelligence", style: "neon" },
  { id: "472", text: "To conquer the unknown, the silent observer finds clarity in the noise.", author: "Apex Intelligence", style: "comic" },
  { id: "473", text: "When variables align, the relentless student strikes with absolute precision.", author: "Apex Intelligence", style: "comic" },
  { id: "474", text: "When variables align, a true master sees what others miss.", author: "Apex Intelligence", style: "biohazard" },
  { id: "475", text: "Where chaos meets order, the apex scholar turns failure into data.", author: "Apex Intelligence", style: "glitch" },
  { id: "476", text: "Through relentless focus, a calculated mind calculates the perfect victory.", author: "Apex Intelligence", style: "glitch" },
  { id: "477", text: "Through relentless focus, a calculated mind calculates the perfect victory.", author: "Apex Intelligence", style: "biohazard" },
  { id: "478", text: "In the arena of logic, the relentless student turns failure into data.", author: "Apex Intelligence", style: "magma" },
  { id: "479", text: "To conquer the unknown, a true master rewrites the rules of the game.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "480", text: "In the architecture of mind, the apex scholar calculates the perfect victory.", author: "Apex Intelligence", style: "brutalist" },
  { id: "481", text: "Through relentless focus, a true master calculates the perfect victory.", author: "Apex Intelligence", style: "biohazard" },
  { id: "482", text: "When variables align, the apex scholar calculates the perfect victory.", author: "Apex Intelligence", style: "magma" },
  { id: "483", text: "Against impossible odds, the relentless student sees what others miss.", author: "Apex Intelligence", style: "hologram" },
  { id: "484", text: "Where chaos meets order, the silent observer strikes with absolute precision.", author: "Apex Intelligence", style: "biohazard" },
  { id: "485", text: "Beyond the infinite, the relentless student strikes with absolute precision.", author: "Apex Intelligence", style: "glitch" },
  { id: "486", text: "In the arena of logic, a calculated mind rewrites the rules of the game.", author: "Apex Intelligence", style: "biohazard" },
  { id: "487", text: "To conquer the unknown, the relentless student calculates the perfect victory.", author: "Apex Intelligence", style: "synthwave" },
  { id: "488", text: "To conquer the unknown, a true master sees what others miss.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "489", text: "Where chaos meets order, the silent observer turns failure into data.", author: "Apex Intelligence", style: "synthwave" },
  { id: "490", text: "Through relentless focus, the apex scholar calculates the perfect victory.", author: "Apex Intelligence", style: "gold" },
  { id: "491", text: "In the arena of logic, the silent observer sees what others miss.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "492", text: "Against impossible odds, a calculated mind strikes with absolute precision.", author: "Apex Intelligence", style: "synthwave" },
  { id: "493", text: "When variables align, the silent observer calculates the perfect victory.", author: "Apex Intelligence", style: "hologram" },
  { id: "494", text: "Beyond the infinite, a true master sees what others miss.", author: "Apex Intelligence", style: "minimal" },
  { id: "495", text: "In the architecture of mind, the architect of fate rewrites the rules of the game.", author: "Apex Intelligence", style: "brutalist" },
  { id: "496", text: "In the arena of logic, the architect of fate calculates the perfect victory.", author: "Apex Intelligence", style: "gold" },
  { id: "497", text: "Against impossible odds, the apex scholar calculates the perfect victory.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "498", text: "Against impossible odds, the relentless student rewrites the rules of the game.", author: "Apex Intelligence", style: "minimal" },
  { id: "499", text: "In the arena of logic, a true master finds clarity in the noise.", author: "Apex Intelligence", style: "hologram" },
  { id: "500", text: "In the architecture of mind, the architect of fate strikes with absolute precision.", author: "Apex Intelligence", style: "magma" },
  { id: "501", text: "Through relentless focus, the apex scholar sees what others miss.", author: "Apex Intelligence", style: "neon" },
  { id: "502", text: "When variables align, a calculated mind calculates the perfect victory.", author: "Apex Intelligence", style: "gold" },
  { id: "503", text: "In the architecture of mind, the apex scholar finds clarity in the noise.", author: "Apex Intelligence", style: "gold" },
  { id: "504", text: "Through relentless focus, the silent observer strikes with absolute precision.", author: "Apex Intelligence", style: "cosmic" },
  { id: "505", text: "Against impossible odds, the silent observer finds clarity in the noise.", author: "Apex Intelligence", style: "brutalist" },
  { id: "506", text: "Where chaos meets order, the relentless student rewrites the rules of the game.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "507", text: "In the architecture of mind, the architect of fate sees what others miss.", author: "Apex Intelligence", style: "glitch" },
  { id: "508", text: "Through relentless focus, a calculated mind turns failure into data.", author: "Apex Intelligence", style: "minimal" },
  { id: "509", text: "Against impossible odds, the architect of fate turns failure into data.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "510", text: "In the arena of logic, the relentless student turns failure into data.", author: "Apex Intelligence", style: "retro" },
  { id: "511", text: "Beyond the infinite, the apex scholar turns failure into data.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "512", text: "In the architecture of mind, the architect of fate rewrites the rules of the game.", author: "Apex Intelligence", style: "neon" },
  { id: "513", text: "Against impossible odds, the architect of fate finds clarity in the noise.", author: "Apex Intelligence", style: "minimal" },
  { id: "514", text: "When variables align, the relentless student sees what others miss.", author: "Apex Intelligence", style: "synthwave" },
  { id: "515", text: "Where chaos meets order, the silent observer strikes with absolute precision.", author: "Apex Intelligence", style: "minimal" },
  { id: "516", text: "To conquer the unknown, the apex scholar calculates the perfect victory.", author: "Apex Intelligence", style: "cosmic" },
  { id: "517", text: "Against impossible odds, a true master calculates the perfect victory.", author: "Apex Intelligence", style: "comic" },
  { id: "518", text: "Through relentless focus, the silent observer strikes with absolute precision.", author: "Apex Intelligence", style: "comic" },
  { id: "519", text: "Through relentless focus, the architect of fate turns failure into data.", author: "Apex Intelligence", style: "magma" },
  { id: "520", text: "Against impossible odds, the architect of fate strikes with absolute precision.", author: "Apex Intelligence", style: "frost" },
  { id: "521", text: "Through relentless focus, the apex scholar finds clarity in the noise.", author: "Apex Intelligence", style: "biohazard" },
  { id: "522", text: "Beyond the infinite, a true master calculates the perfect victory.", author: "Apex Intelligence", style: "retro" },
  { id: "523", text: "Against impossible odds, the architect of fate turns failure into data.", author: "Apex Intelligence", style: "frost" },
  { id: "524", text: "In the arena of logic, a calculated mind finds clarity in the noise.", author: "Apex Intelligence", style: "comic" },
  { id: "525", text: "Against impossible odds, a calculated mind finds clarity in the noise.", author: "Apex Intelligence", style: "neon" },
  { id: "526", text: "Against impossible odds, a true master turns failure into data.", author: "Apex Intelligence", style: "neon" },
  { id: "527", text: "When variables align, the apex scholar finds clarity in the noise.", author: "Apex Intelligence", style: "frost" },
  { id: "528", text: "Against impossible odds, the silent observer finds clarity in the noise.", author: "Apex Intelligence", style: "comic" },
  { id: "529", text: "Where chaos meets order, the silent observer sees what others miss.", author: "Apex Intelligence", style: "gold" },
  { id: "530", text: "Through relentless focus, the relentless student turns failure into data.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "531", text: "To conquer the unknown, the apex scholar finds clarity in the noise.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "532", text: "Where chaos meets order, the relentless student turns failure into data.", author: "Apex Intelligence", style: "glitch" },
  { id: "533", text: "Beyond the infinite, the architect of fate rewrites the rules of the game.", author: "Apex Intelligence", style: "magma" },
  { id: "534", text: "In the architecture of mind, the silent observer rewrites the rules of the game.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "535", text: "Beyond the infinite, the apex scholar turns failure into data.", author: "Apex Intelligence", style: "brutalist" },
  { id: "536", text: "In the arena of logic, a calculated mind sees what others miss.", author: "Apex Intelligence", style: "glitch" },
  { id: "537", text: "Where chaos meets order, the relentless student rewrites the rules of the game.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "538", text: "In the architecture of mind, the silent observer strikes with absolute precision.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "539", text: "Where chaos meets order, the apex scholar turns failure into data.", author: "Apex Intelligence", style: "retro" },
  { id: "540", text: "Through relentless focus, the apex scholar sees what others miss.", author: "Apex Intelligence", style: "retro" },
  { id: "541", text: "Through relentless focus, the silent observer calculates the perfect victory.", author: "Apex Intelligence", style: "synthwave" },
  { id: "542", text: "In the architecture of mind, the relentless student sees what others miss.", author: "Apex Intelligence", style: "hologram" },
  { id: "543", text: "Where chaos meets order, a true master strikes with absolute precision.", author: "Apex Intelligence", style: "glitch" },
  { id: "544", text: "Through relentless focus, the architect of fate finds clarity in the noise.", author: "Apex Intelligence", style: "frost" },
  { id: "545", text: "To conquer the unknown, a calculated mind turns failure into data.", author: "Apex Intelligence", style: "retro" },
  { id: "546", text: "In the architecture of mind, the architect of fate rewrites the rules of the game.", author: "Apex Intelligence", style: "brutalist" },
  { id: "547", text: "When variables align, a true master finds clarity in the noise.", author: "Apex Intelligence", style: "cosmic" },
  { id: "548", text: "Through relentless focus, the architect of fate sees what others miss.", author: "Apex Intelligence", style: "biohazard" },
  { id: "549", text: "In the architecture of mind, the relentless student sees what others miss.", author: "Apex Intelligence", style: "hologram" },
  { id: "550", text: "Against impossible odds, the apex scholar sees what others miss.", author: "Apex Intelligence", style: "frost" },
  { id: "551", text: "Beyond the infinite, the apex scholar turns failure into data.", author: "Apex Intelligence", style: "brutalist" },
  { id: "552", text: "When variables align, the architect of fate turns failure into data.", author: "Apex Intelligence", style: "gold" },
  { id: "553", text: "To conquer the unknown, the relentless student rewrites the rules of the game.", author: "Apex Intelligence", style: "glitch" },
  { id: "554", text: "In the architecture of mind, a true master finds clarity in the noise.", author: "Apex Intelligence", style: "comic" },
  { id: "555", text: "In the architecture of mind, the relentless student strikes with absolute precision.", author: "Apex Intelligence", style: "synthwave" },
  { id: "556", text: "Through relentless focus, a true master strikes with absolute precision.", author: "Apex Intelligence", style: "cosmic" },
  { id: "557", text: "Beyond the infinite, the architect of fate strikes with absolute precision.", author: "Apex Intelligence", style: "cosmic" },
  { id: "558", text: "Where chaos meets order, the silent observer strikes with absolute precision.", author: "Apex Intelligence", style: "retro" },
  { id: "559", text: "To conquer the unknown, the relentless student strikes with absolute precision.", author: "Apex Intelligence", style: "biohazard" },
  { id: "560", text: "Where chaos meets order, the architect of fate sees what others miss.", author: "Apex Intelligence", style: "minimal" },
  { id: "561", text: "Through relentless focus, the relentless student turns failure into data.", author: "Apex Intelligence", style: "glitch" },
  { id: "562", text: "To conquer the unknown, the architect of fate rewrites the rules of the game.", author: "Apex Intelligence", style: "minimal" },
  { id: "563", text: "Through relentless focus, a calculated mind sees what others miss.", author: "Apex Intelligence", style: "glitch" },
  { id: "564", text: "In the architecture of mind, the apex scholar rewrites the rules of the game.", author: "Apex Intelligence", style: "synthwave" },
  { id: "565", text: "Where chaos meets order, the silent observer rewrites the rules of the game.", author: "Apex Intelligence", style: "hologram" },
  { id: "566", text: "Beyond the infinite, the architect of fate calculates the perfect victory.", author: "Apex Intelligence", style: "hologram" },
  { id: "567", text: "In the arena of logic, the relentless student strikes with absolute precision.", author: "Apex Intelligence", style: "comic" },
  { id: "568", text: "Against impossible odds, the architect of fate strikes with absolute precision.", author: "Apex Intelligence", style: "cosmic" },
  { id: "569", text: "In the arena of logic, the silent observer calculates the perfect victory.", author: "Apex Intelligence", style: "cosmic" },
  { id: "570", text: "Through relentless focus, the apex scholar strikes with absolute precision.", author: "Apex Intelligence", style: "brutalist" },
  { id: "571", text: "To conquer the unknown, a calculated mind strikes with absolute precision.", author: "Apex Intelligence", style: "glitch" },
  { id: "572", text: "When variables align, a calculated mind calculates the perfect victory.", author: "Apex Intelligence", style: "glitch" },
  { id: "573", text: "In the arena of logic, the silent observer turns failure into data.", author: "Apex Intelligence", style: "gold" },
  { id: "574", text: "Beyond the infinite, the architect of fate rewrites the rules of the game.", author: "Apex Intelligence", style: "gold" },
  { id: "575", text: "Beyond the infinite, a calculated mind finds clarity in the noise.", author: "Apex Intelligence", style: "frost" },
  { id: "576", text: "When variables align, the apex scholar sees what others miss.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "577", text: "Through relentless focus, the silent observer sees what others miss.", author: "Apex Intelligence", style: "gold" },
  { id: "578", text: "Beyond the infinite, a true master turns failure into data.", author: "Apex Intelligence", style: "cosmic" },
  { id: "579", text: "In the arena of logic, a calculated mind calculates the perfect victory.", author: "Apex Intelligence", style: "neon" },
  { id: "580", text: "Through relentless focus, the apex scholar rewrites the rules of the game.", author: "Apex Intelligence", style: "magma" },
  { id: "581", text: "In the architecture of mind, a calculated mind rewrites the rules of the game.", author: "Apex Intelligence", style: "synthwave" },
  { id: "582", text: "In the arena of logic, the silent observer turns failure into data.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "583", text: "In the arena of logic, the silent observer finds clarity in the noise.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "584", text: "In the architecture of mind, the apex scholar finds clarity in the noise.", author: "Apex Intelligence", style: "glitch" },
  { id: "585", text: "In the architecture of mind, the relentless student turns failure into data.", author: "Apex Intelligence", style: "biohazard" },
  { id: "586", text: "When variables align, a calculated mind finds clarity in the noise.", author: "Apex Intelligence", style: "brutalist" },
  { id: "587", text: "Through relentless focus, the architect of fate sees what others miss.", author: "Apex Intelligence", style: "glassmorphism" },
  { id: "588", text: "Beyond the infinite, the silent observer sees what others miss.", author: "Apex Intelligence", style: "gold" },
  { id: "589", text: "In the architecture of mind, the relentless student rewrites the rules of the game.", author: "Apex Intelligence", style: "hologram" },
  { id: "590", text: "When variables align, the relentless student finds clarity in the noise.", author: "Apex Intelligence", style: "hologram" },
  { id: "591", text: "In the architecture of mind, the relentless student strikes with absolute precision.", author: "Apex Intelligence", style: "synthwave" },
  { id: "592", text: "In the architecture of mind, the silent observer strikes with absolute precision.", author: "Apex Intelligence", style: "cosmic" },
  { id: "593", text: "Beyond the infinite, the silent observer rewrites the rules of the game.", author: "Apex Intelligence", style: "hologram" },
  { id: "594", text: "Through relentless focus, the architect of fate turns failure into data.", author: "Apex Intelligence", style: "cosmic" },
  { id: "595", text: "Beyond the infinite, a calculated mind turns failure into data.", author: "Apex Intelligence", style: "synthwave" },
  { id: "596", text: "To conquer the unknown, a true master turns failure into data.", author: "Apex Intelligence", style: "gold" },
  { id: "597", text: "When variables align, the apex scholar turns failure into data.", author: "Apex Intelligence", style: "hologram" },
  { id: "598", text: "In the arena of logic, the apex scholar strikes with absolute precision.", author: "Apex Intelligence", style: "cyberpunk" },
  { id: "599", text: "Beyond the infinite, a true master strikes with absolute precision.", author: "Apex Intelligence", style: "frost" },
];
