"""Add UserLootbox and expand CollectiblesDictionary

Revision ID: 6a820867f848
Revises: bc4b5accfc8f
Create Date: 2026-07-09 17:00:06.009383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a820867f848'
down_revision: Union[str, Sequence[str], None] = 'bc4b5accfc8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lootboxes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('box_type', sa.String(length=50), nullable=False),
    sa.Column('acquired_via', sa.String(length=100), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_lootboxes_user_id'), 'user_lootboxes', ['user_id'], unique=False)
    op.add_column('collectibles_dictionary', sa.Column('type', sa.String(length=50), server_default='AVATAR', nullable=False))
    op.add_column('collectibles_dictionary', sa.Column('series', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collectibles_dictionary', 'series')
    op.drop_column('collectibles_dictionary', 'type')
    op.drop_index(op.f('ix_user_lootboxes_user_id'), table_name='user_lootboxes')
    op.drop_table('user_lootboxes')
    # ### end Alembic commands ###
