"""Add Gamification and Economy schemas

Revision ID: 9d8315cb5f08
Revises: 18fa414af0ad
Create Date: 2026-07-07 18:49:32.363209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8315cb5f08'
down_revision: Union[str, Sequence[str], None] = '18fa414af0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collectibles_dictionary',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('model_3d_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('economy_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount_xp', sa.Integer(), nullable=False),
    sa.Column('amount_coins', sa.Integer(), nullable=False),
    sa.Column('source_action', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economy_transactions_reference_id'), 'economy_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_economy_transactions_user_id'), 'economy_transactions', ['user_id'], unique=False)
    op.create_table('user_collectibles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('collectible_id', sa.String(), nullable=False),
    sa.Column('acquired_via', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['collectible_id'], ['collectibles_dictionary.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_collectibles_collectible_id'), 'user_collectibles', ['collectible_id'], unique=False)
    op.create_index(op.f('ix_user_collectibles_user_id'), 'user_collectibles', ['user_id'], unique=False)
    op.create_table('user_economy',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('current_rank_tier', sa.String(length=50), nullable=False),
    sa.Column('coin_balance', sa.Integer(), nullable=False),
    sa.Column('lifetime_coins_earned', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_economy_user_id'), 'user_economy', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_economy_user_id'), table_name='user_economy')
    op.drop_table('user_economy')
    op.drop_index(op.f('ix_user_collectibles_user_id'), table_name='user_collectibles')
    op.drop_index(op.f('ix_user_collectibles_collectible_id'), table_name='user_collectibles')
    op.drop_table('user_collectibles')
    op.drop_index(op.f('ix_economy_transactions_user_id'), table_name='economy_transactions')
    op.drop_index(op.f('ix_economy_transactions_reference_id'), table_name='economy_transactions')
    op.drop_table('economy_transactions')
    op.drop_table('collectibles_dictionary')
    # ### end Alembic commands ###
