"""add quantum_fragments to user_economy

Revision ID: abe776eff8ee
Revises: 6a820867f848
Create Date: 2026-07-09 17:55:37.580901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe776eff8ee'
down_revision: Union[str, Sequence[str], None] = '6a820867f848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_economy', sa.Column('quantum_fragments', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_economy', 'quantum_fragments')
    # ### end Alembic commands ###
