"""Add last_active_at to users

Revision ID: bc4b5accfc8f
Revises: 9d8315cb5f08
Create Date: 2026-07-08 14:28:56.069609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4b5accfc8f'
down_revision: Union[str, Sequence[str], None] = '9d8315cb5f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    # ### end Alembic commands ###
